// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable

namespace FishyFlip.Lexicon
{
    /// <summary>
    /// FishyFlip ATError for RepoNotFound.
    /// </summary>
    public class RepoNotFoundError : FishyFlip.Models.ATError
    {
        public RepoNotFoundError(int statusCode, ErrorDetail detail) : base(statusCode, detail)
        {
        }
    }
}

