// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon
{
    /// <summary>
    /// FishyFlip ATError for RuleNotFound.
    /// </summary>
    public class RuleNotFoundError : FishyFlip.Models.ATError
    {
        public RuleNotFoundError(int statusCode, ErrorDetail detail) : base(statusCode, detail)
        {
        }
    }
}

