// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Ageassurance
{
    /// <summary>
    /// Age Assurance rule that applies if the user has declared themselves under a certain age.
    /// </summary>
    public partial class ConfigRegionRuleIfDeclaredUnderAge : ATObject, ICBOREncodable<ConfigRegionRuleIfDeclaredUnderAge>, IJsonEncodable<ConfigRegionRuleIfDeclaredUnderAge>, IParsable<ConfigRegionRuleIfDeclaredUnderAge>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigRegionRuleIfDeclaredUnderAge"/> class.
        /// </summary>
        /// <param name="age">The age threshold as a whole integer.</param>
        /// <param name="access">
        /// <br/> Known Values: <br/>
        /// unknown <br/>
        /// none <br/>
        /// safe <br/>
        /// full <br/>
        /// </param>
        public ConfigRegionRuleIfDeclaredUnderAge(long age = default, string access = default)
        {
            this.Age = age;
            this.Access = access;
            this.Type = "app.bsky.ageassurance.defs#configRegionRuleIfDeclaredUnderAge";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigRegionRuleIfDeclaredUnderAge"/> class.
        /// </summary>
        public ConfigRegionRuleIfDeclaredUnderAge()
        {
            this.Type = "app.bsky.ageassurance.defs#configRegionRuleIfDeclaredUnderAge";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigRegionRuleIfDeclaredUnderAge"/> class.
        /// </summary>
        public ConfigRegionRuleIfDeclaredUnderAge(CBORObject obj)
        {
            if (obj["age"] is not null) this.Age = obj["age"].AsInt64Value();
            if (obj["access"] is not null) this.Access = obj["access"].AsString();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the age.
        /// <br/> The age threshold as a whole integer.
        /// </summary>
        [JsonPropertyName("age")]
        [JsonRequired]
        public long Age { get; set; }

        /// <summary>
        /// Gets or sets the access.
        /// <br/> Known Values: <br/>
        /// unknown <br/>
        /// none <br/>
        /// safe <br/>
        /// full <br/>
        /// </summary>
        [JsonPropertyName("access")]
        [JsonRequired]
        public string Access { get; set; }

        public const string RecordType = "app.bsky.ageassurance.defs#configRegionRuleIfDeclaredUnderAge";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Ageassurance.ConfigRegionRuleIfDeclaredUnderAge>)SourceGenerationContext.Default.AppBskyAgeassuranceConfigRegionRuleIfDeclaredUnderAge);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Ageassurance.ConfigRegionRuleIfDeclaredUnderAge>)SourceGenerationContext.Default.AppBskyAgeassuranceConfigRegionRuleIfDeclaredUnderAge);
        }

        public static new ConfigRegionRuleIfDeclaredUnderAge FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Ageassurance.ConfigRegionRuleIfDeclaredUnderAge>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Ageassurance.ConfigRegionRuleIfDeclaredUnderAge>)SourceGenerationContext.Default.AppBskyAgeassuranceConfigRegionRuleIfDeclaredUnderAge)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new ConfigRegionRuleIfDeclaredUnderAge FromCBORObject(CBORObject obj)
        {
            return new ConfigRegionRuleIfDeclaredUnderAge(obj);
        }

        /// <inheritdoc/>
        public static ConfigRegionRuleIfDeclaredUnderAge Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<ConfigRegionRuleIfDeclaredUnderAge>(s, (JsonTypeInfo<ConfigRegionRuleIfDeclaredUnderAge>)SourceGenerationContext.Default.AppBskyAgeassuranceConfigRegionRuleIfDeclaredUnderAge)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out ConfigRegionRuleIfDeclaredUnderAge result)
        {
            result = JsonSerializer.Deserialize<ConfigRegionRuleIfDeclaredUnderAge>(s, (JsonTypeInfo<ConfigRegionRuleIfDeclaredUnderAge>)SourceGenerationContext.Default.AppBskyAgeassuranceConfigRegionRuleIfDeclaredUnderAge);
            return result != null;
        }
    }
}

