// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Graph
{
    public partial class UnmuteThreadInput : ATObject, ICBOREncodable<UnmuteThreadInput>, IJsonEncodable<UnmuteThreadInput>, IParsable<UnmuteThreadInput>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="UnmuteThreadInput"/> class.
        /// </summary>
        /// <param name="root"></param>
        public UnmuteThreadInput(FishyFlip.Models.ATUri root = default)
        {
            this.Root = root;
            this.Type = "app.bsky.graph.unmuteThread#UnmuteThreadInput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="UnmuteThreadInput"/> class.
        /// </summary>
        public UnmuteThreadInput()
        {
            this.Type = "app.bsky.graph.unmuteThread#UnmuteThreadInput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="UnmuteThreadInput"/> class.
        /// </summary>
        public UnmuteThreadInput(CBORObject obj)
        {
            if (obj["root"] is not null) this.Root = obj["root"].ToATUri();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the root.
        /// </summary>
        [JsonPropertyName("root")]
        [JsonRequired]
        [JsonConverter(typeof(FishyFlip.Tools.Json.ATUriJsonConverter))]
        public FishyFlip.Models.ATUri Root { get; set; }

        public const string RecordType = "app.bsky.graph.unmuteThread#UnmuteThreadInput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Graph.UnmuteThreadInput>)SourceGenerationContext.Default.AppBskyGraphUnmuteThreadInput);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Graph.UnmuteThreadInput>)SourceGenerationContext.Default.AppBskyGraphUnmuteThreadInput);
        }

        public static new UnmuteThreadInput FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Graph.UnmuteThreadInput>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Graph.UnmuteThreadInput>)SourceGenerationContext.Default.AppBskyGraphUnmuteThreadInput)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new UnmuteThreadInput FromCBORObject(CBORObject obj)
        {
            return new UnmuteThreadInput(obj);
        }

        /// <inheritdoc/>
        public static UnmuteThreadInput Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<UnmuteThreadInput>(s, (JsonTypeInfo<UnmuteThreadInput>)SourceGenerationContext.Default.AppBskyGraphUnmuteThreadInput)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out UnmuteThreadInput result)
        {
            result = JsonSerializer.Deserialize<UnmuteThreadInput>(s, (JsonTypeInfo<UnmuteThreadInput>)SourceGenerationContext.Default.AppBskyGraphUnmuteThreadInput);
            return result != null;
        }
    }
}

