// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Graph
{
    public partial class UnmuteActorInput : ATObject, ICBOREncodable<UnmuteActorInput>, IJsonEncodable<UnmuteActorInput>, IParsable<UnmuteActorInput>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="UnmuteActorInput"/> class.
        /// </summary>
        /// <param name="actor"></param>
        public UnmuteActorInput(FishyFlip.Models.ATIdentifier actor = default)
        {
            this.Actor = actor;
            this.Type = "app.bsky.graph.unmuteActor#UnmuteActorInput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="UnmuteActorInput"/> class.
        /// </summary>
        public UnmuteActorInput()
        {
            this.Type = "app.bsky.graph.unmuteActor#UnmuteActorInput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="UnmuteActorInput"/> class.
        /// </summary>
        public UnmuteActorInput(CBORObject obj)
        {
            if (obj["actor"] is not null) this.Actor = obj["actor"].ToATIdentifier();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the actor.
        /// </summary>
        [JsonPropertyName("actor")]
        [JsonRequired]
        [JsonConverter(typeof(FishyFlip.Tools.Json.ATIdentifierJsonConverter))]
        public FishyFlip.Models.ATIdentifier Actor { get; set; }

        public const string RecordType = "app.bsky.graph.unmuteActor#UnmuteActorInput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Graph.UnmuteActorInput>)SourceGenerationContext.Default.AppBskyGraphUnmuteActorInput);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Graph.UnmuteActorInput>)SourceGenerationContext.Default.AppBskyGraphUnmuteActorInput);
        }

        public static new UnmuteActorInput FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Graph.UnmuteActorInput>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Graph.UnmuteActorInput>)SourceGenerationContext.Default.AppBskyGraphUnmuteActorInput)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new UnmuteActorInput FromCBORObject(CBORObject obj)
        {
            return new UnmuteActorInput(obj);
        }

        /// <inheritdoc/>
        public static UnmuteActorInput Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<UnmuteActorInput>(s, (JsonTypeInfo<UnmuteActorInput>)SourceGenerationContext.Default.AppBskyGraphUnmuteActorInput)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out UnmuteActorInput result)
        {
            result = JsonSerializer.Deserialize<UnmuteActorInput>(s, (JsonTypeInfo<UnmuteActorInput>)SourceGenerationContext.Default.AppBskyGraphUnmuteActorInput);
            return result != null;
        }
    }
}

