// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable

namespace FishyFlip.Lexicon.Com.Atproto.Temp
{
    public partial class CheckSignupQueueOutput : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="CheckSignupQueueOutput"/> class.
        /// </summary>
        public CheckSignupQueueOutput(bool? activated = default, long? placeInQueue = default, long? estimatedTimeMs = default)
        {
            this.Activated = activated;
            this.PlaceInQueue = placeInQueue;
            this.EstimatedTimeMs = estimatedTimeMs;
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="CheckSignupQueueOutput"/> class.
        /// </summary>
        public CheckSignupQueueOutput()
        {
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="CheckSignupQueueOutput"/> class.
        /// </summary>
        public CheckSignupQueueOutput(CBORObject obj)
        {
            if (obj["activated"] is not null) this.Activated = obj["activated"].AsBoolean();
            if (obj["placeInQueue"] is not null) this.PlaceInQueue = obj["placeInQueue"].AsInt64Value();
            if (obj["estimatedTimeMs"] is not null) this.EstimatedTimeMs = obj["estimatedTimeMs"].AsInt64Value();
        }

        [JsonPropertyName("activated")]
        [JsonRequired]
        public bool? Activated { get; set; }

        [JsonPropertyName("placeInQueue")]
        public long? PlaceInQueue { get; set; }

        [JsonPropertyName("estimatedTimeMs")]
        public long? EstimatedTimeMs { get; set; }

        /// <summary>
        /// Gets the ATRecord Type.
        /// </summary>
        [JsonPropertyName("$type")]
        public override string Type => "com.atproto.temp.checkSignupQueue#CheckSignupQueueOutput";

        public const string RecordType = "com.atproto.temp.checkSignupQueue#CheckSignupQueueOutput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize<Com.Atproto.Temp.CheckSignupQueueOutput>(this, (JsonTypeInfo<Com.Atproto.Temp.CheckSignupQueueOutput>)SourceGenerationContext.Default.ComAtprotoTempCheckSignupQueueOutput)!;
        }

        public static CheckSignupQueueOutput FromJson(string json)
        {
            return JsonSerializer.Deserialize<Com.Atproto.Temp.CheckSignupQueueOutput>(json, (JsonTypeInfo<Com.Atproto.Temp.CheckSignupQueueOutput>)SourceGenerationContext.Default.ComAtprotoTempCheckSignupQueueOutput)!;
        }
    }
}

