// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Labeler
{
    public partial class LabelerPolicies : ATObject, ICBOREncodable<LabelerPolicies>, IJsonEncodable<LabelerPolicies>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="LabelerPolicies"/> class.
        /// </summary>
        /// <param name="labelValues">The label values which this labeler publishes. May include global or custom labels.</param>
        /// <param name="labelValueDefinitions">Label values created by this labeler and scoped exclusively to it. Labels defined here will override global label definitions for this labeler.</param>
        public LabelerPolicies(List<string> labelValues = default, List<FishyFlip.Lexicon.Com.Atproto.Label.LabelValueDefinition>? labelValueDefinitions = default)
        {
            this.LabelValues = labelValues;
            this.LabelValueDefinitions = labelValueDefinitions;
            this.Type = "app.bsky.labeler.defs#labelerPolicies";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="LabelerPolicies"/> class.
        /// </summary>
        public LabelerPolicies()
        {
            this.Type = "app.bsky.labeler.defs#labelerPolicies";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="LabelerPolicies"/> class.
        /// </summary>
        public LabelerPolicies(CBORObject obj)
        {
            if (obj["labelValues"] is not null) this.LabelValues = obj["labelValues"].Values.Select(n =>n.AsString()).ToList();
            if (obj["labelValueDefinitions"] is not null) this.LabelValueDefinitions = obj["labelValueDefinitions"].Values.Select(n =>new FishyFlip.Lexicon.Com.Atproto.Label.LabelValueDefinition(n)).ToList();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the labelValues.
        /// <br/> The label values which this labeler publishes. May include global or custom labels.
        /// </summary>
        [JsonPropertyName("labelValues")]
        [JsonRequired]
        public List<string> LabelValues { get; set; }

        /// <summary>
        /// Gets or sets the labelValueDefinitions.
        /// <br/> Label values created by this labeler and scoped exclusively to it. Labels defined here will override global label definitions for this labeler.
        /// </summary>
        [JsonPropertyName("labelValueDefinitions")]
        public List<FishyFlip.Lexicon.Com.Atproto.Label.LabelValueDefinition>? LabelValueDefinitions { get; set; }

        public const string RecordType = "app.bsky.labeler.defs#labelerPolicies";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Labeler.LabelerPolicies>)SourceGenerationContext.Default.AppBskyLabelerLabelerPolicies);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Labeler.LabelerPolicies>)SourceGenerationContext.Default.AppBskyLabelerLabelerPolicies);
        }

        public static new LabelerPolicies FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Labeler.LabelerPolicies>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Labeler.LabelerPolicies>)SourceGenerationContext.Default.AppBskyLabelerLabelerPolicies)!;
        }

         /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

         /// <inheritdoc/>
        public static new LabelerPolicies FromCBORObject(CBORObject obj)
        {
            return new LabelerPolicies(obj);
        }

    }
}

