// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable

namespace FishyFlip.Lexicon.App.Bsky.Embed
{
    public partial class EmbedRecord : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="EmbedRecord"/> class.
        /// </summary>
        public EmbedRecord()
        {
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="EmbedRecord"/> class.
        /// </summary>
        public EmbedRecord(CBORObject obj)
        {
            if (obj["record"] is not null) this.Record = new FishyFlip.Lexicon.Com.Atproto.Repo.StrongRef(obj["record"]);
        }

        [JsonPropertyName("record")]
        [JsonRequired]
        public Com.Atproto.Repo.StrongRef? Record { get; set; }

        /// <summary>
        /// Gets the ATRecord Type.
        /// </summary>
        [JsonPropertyName("$type")]
        public override string Type => "app.bsky.embed.record";

        public const string RecordType = "app.bsky.embed.record";

        public override string ToJson()
        {
            return JsonSerializer.Serialize<App.Bsky.Embed.EmbedRecord>(this, (JsonTypeInfo<App.Bsky.Embed.EmbedRecord>)SourceGenerationContext.Default.AppBskyEmbedEmbedRecord)!;
        }

        public static EmbedRecord FromJson(string json)
        {
            return JsonSerializer.Deserialize<App.Bsky.Embed.EmbedRecord>(json, (JsonTypeInfo<App.Bsky.Embed.EmbedRecord>)SourceGenerationContext.Default.AppBskyEmbedEmbedRecord)!;
        }
    }
}

