// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable

namespace FishyFlip.Lexicon.App.Bsky.Embed
{
    public partial class ViewVideo : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="ViewVideo"/> class.
        /// </summary>
        public ViewVideo()
        {
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="ViewVideo"/> class.
        /// </summary>
        public ViewVideo(CBORObject obj)
        {
            if (obj["cid"] is not null) this.Cid = obj["cid"].AsString();
            if (obj["playlist"] is not null) this.Playlist = obj["playlist"].AsString();
            if (obj["thumbnail"] is not null) this.Thumbnail = obj["thumbnail"].AsString();
            if (obj["alt"] is not null) this.Alt = obj["alt"].AsString();
            if (obj["aspectRatio"] is not null) this.AspectRatio = new App.Bsky.Embed.AspectRatio(obj["aspectRatio"]);
        }

        [JsonPropertyName("cid")]
        [JsonRequired]
        public string? Cid { get; set; }

        [JsonPropertyName("playlist")]
        [JsonRequired]
        public string? Playlist { get; set; }

        [JsonPropertyName("thumbnail")]
        public string? Thumbnail { get; set; }

        [JsonPropertyName("alt")]
        public string? Alt { get; set; }

        [JsonPropertyName("aspectRatio")]
        public App.Bsky.Embed.AspectRatio? AspectRatio { get; set; }

        /// <summary>
        /// Gets the ATRecord Type.
        /// </summary>
        [JsonPropertyName("$type")]
        public override string Type => "app.bsky.embed.video#view";

        public const string RecordType = "app.bsky.embed.video#view";

        public override string ToJson()
        {
            return JsonSerializer.Serialize<App.Bsky.Embed.ViewVideo>(this, (JsonTypeInfo<App.Bsky.Embed.ViewVideo>)SourceGenerationContext.Default.AppBskyEmbedViewVideo)!;
        }

        public static ViewVideo FromJson(string json)
        {
            return JsonSerializer.Deserialize<App.Bsky.Embed.ViewVideo>(json, (JsonTypeInfo<App.Bsky.Embed.ViewVideo>)SourceGenerationContext.Default.AppBskyEmbedViewVideo)!;
        }
    }
}

