// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable

namespace FishyFlip.Lexicon.App.Bsky.Embed
{
    public partial class ViewImages : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="ViewImages"/> class.
        /// </summary>
        public ViewImages()
        {
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="ViewImages"/> class.
        /// </summary>
        public ViewImages(CBORObject obj)
        {
            if (obj["images"] is not null) this.Images = obj["images"].Values.Select(n =>new App.Bsky.Embed.ViewImage(n)).ToList();
        }

        [JsonPropertyName("images")]
        [JsonRequired]
        public List<App.Bsky.Embed.ViewImage>? Images { get; set; }

        /// <summary>
        /// Gets the ATRecord Type.
        /// </summary>
        [JsonPropertyName("$type")]
        public override string Type => "app.bsky.embed.images#view";

        public const string RecordType = "app.bsky.embed.images#view";

        public override string ToJson()
        {
            return JsonSerializer.Serialize<App.Bsky.Embed.ViewImages>(this, (JsonTypeInfo<App.Bsky.Embed.ViewImages>)SourceGenerationContext.Default.AppBskyEmbedViewImages)!;
        }

        public static ViewImages FromJson(string json)
        {
            return JsonSerializer.Deserialize<App.Bsky.Embed.ViewImages>(json, (JsonTypeInfo<App.Bsky.Embed.ViewImages>)SourceGenerationContext.Default.AppBskyEmbedViewImages)!;
        }
    }
}

