// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Actor
{
    public partial class GetProfilesOutput : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="GetProfilesOutput"/> class.
        /// </summary>
        /// <param name="profiles"></param>
        public GetProfilesOutput(List<FishyFlip.Lexicon.App.Bsky.Actor.ProfileViewDetailed> profiles = default)
        {
            this.Profiles = profiles;
            this.Type = "app.bsky.actor.getProfiles#GetProfilesOutput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="GetProfilesOutput"/> class.
        /// </summary>
        public GetProfilesOutput()
        {
            this.Type = "app.bsky.actor.getProfiles#GetProfilesOutput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="GetProfilesOutput"/> class.
        /// </summary>
        public GetProfilesOutput(CBORObject obj)
        {
            if (obj["profiles"] is not null) this.Profiles = obj["profiles"].Values.Select(n =>new FishyFlip.Lexicon.App.Bsky.Actor.ProfileViewDetailed(n)).ToList();
        }

        /// <summary>
        /// Gets or sets the profiles.
        /// </summary>
        [JsonPropertyName("profiles")]
        [JsonRequired]
        public List<FishyFlip.Lexicon.App.Bsky.Actor.ProfileViewDetailed> Profiles { get; set; }

        public const string RecordType = "app.bsky.actor.getProfiles#GetProfilesOutput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize<FishyFlip.Lexicon.App.Bsky.Actor.GetProfilesOutput>(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Actor.GetProfilesOutput>)SourceGenerationContext.Default.AppBskyActorGetProfilesOutput)!;
        }

        public static GetProfilesOutput FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Actor.GetProfilesOutput>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Actor.GetProfilesOutput>)SourceGenerationContext.Default.AppBskyActorGetProfilesOutput)!;
        }
    }
}

