// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Actor
{
    public partial class InterestsPref : ATObject, ICBOREncodable<InterestsPref>, IJsonEncodable<InterestsPref>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="InterestsPref"/> class.
        /// </summary>
        /// <param name="tags">A list of tags which describe the account owner's interests gathered during onboarding.</param>
        public InterestsPref(List<string> tags = default)
        {
            this.Tags = tags;
            this.Type = "app.bsky.actor.defs#interestsPref";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="InterestsPref"/> class.
        /// </summary>
        public InterestsPref()
        {
            this.Type = "app.bsky.actor.defs#interestsPref";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="InterestsPref"/> class.
        /// </summary>
        public InterestsPref(CBORObject obj)
        {
            if (obj["tags"] is not null) this.Tags = obj["tags"].Values.Select(n =>n.AsString()).ToList();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the tags.
        /// <br/> A list of tags which describe the account owner's interests gathered during onboarding.
        /// </summary>
        [JsonPropertyName("tags")]
        [JsonRequired]
        public List<string> Tags { get; set; }

        public const string RecordType = "app.bsky.actor.defs#interestsPref";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Actor.InterestsPref>)SourceGenerationContext.Default.AppBskyActorInterestsPref);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Actor.InterestsPref>)SourceGenerationContext.Default.AppBskyActorInterestsPref);
        }

        public static new InterestsPref FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Actor.InterestsPref>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Actor.InterestsPref>)SourceGenerationContext.Default.AppBskyActorInterestsPref)!;
        }

         /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

         /// <inheritdoc/>
        public static new InterestsPref FromCBORObject(CBORObject obj)
        {
            return new InterestsPref(obj);
        }

    }
}

