// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Actor
{
    public partial class ProfileAssociatedActivitySubscription : ATObject, ICBOREncodable<ProfileAssociatedActivitySubscription>, IJsonEncodable<ProfileAssociatedActivitySubscription>, IParsable<ProfileAssociatedActivitySubscription>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileAssociatedActivitySubscription"/> class.
        /// </summary>
        /// <param name="allowSubscriptions">
        /// <br/> Known Values: <br/>
        /// followers <br/>
        /// mutuals <br/>
        /// none <br/>
        /// </param>
        public ProfileAssociatedActivitySubscription(string allowSubscriptions = default)
        {
            this.AllowSubscriptions = allowSubscriptions;
            this.Type = "app.bsky.actor.defs#profileAssociatedActivitySubscription";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileAssociatedActivitySubscription"/> class.
        /// </summary>
        public ProfileAssociatedActivitySubscription()
        {
            this.Type = "app.bsky.actor.defs#profileAssociatedActivitySubscription";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileAssociatedActivitySubscription"/> class.
        /// </summary>
        public ProfileAssociatedActivitySubscription(CBORObject obj)
        {
            if (obj["allowSubscriptions"] is not null) this.AllowSubscriptions = obj["allowSubscriptions"].AsString();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the allowSubscriptions.
        /// <br/> Known Values: <br/>
        /// followers <br/>
        /// mutuals <br/>
        /// none <br/>
        /// </summary>
        [JsonPropertyName("allowSubscriptions")]
        [JsonRequired]
        public string AllowSubscriptions { get; set; }

        public const string RecordType = "app.bsky.actor.defs#profileAssociatedActivitySubscription";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Actor.ProfileAssociatedActivitySubscription>)SourceGenerationContext.Default.AppBskyActorProfileAssociatedActivitySubscription);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Actor.ProfileAssociatedActivitySubscription>)SourceGenerationContext.Default.AppBskyActorProfileAssociatedActivitySubscription);
        }

        public static new ProfileAssociatedActivitySubscription FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Actor.ProfileAssociatedActivitySubscription>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Actor.ProfileAssociatedActivitySubscription>)SourceGenerationContext.Default.AppBskyActorProfileAssociatedActivitySubscription)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new ProfileAssociatedActivitySubscription FromCBORObject(CBORObject obj)
        {
            return new ProfileAssociatedActivitySubscription(obj);
        }

        /// <inheritdoc/>
        public static ProfileAssociatedActivitySubscription Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<ProfileAssociatedActivitySubscription>(s, (JsonTypeInfo<ProfileAssociatedActivitySubscription>)SourceGenerationContext.Default.AppBskyActorProfileAssociatedActivitySubscription)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out ProfileAssociatedActivitySubscription result)
        {
            result = JsonSerializer.Deserialize<ProfileAssociatedActivitySubscription>(s, (JsonTypeInfo<ProfileAssociatedActivitySubscription>)SourceGenerationContext.Default.AppBskyActorProfileAssociatedActivitySubscription);
            return result != null;
        }
    }
}

