// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable

namespace FishyFlip.Lexicon.App.Bsky.Actor
{
    public partial class SearchActorsTypeaheadOutput : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchActorsTypeaheadOutput"/> class.
        /// </summary>
        /// <param name="actors"></param>
        public SearchActorsTypeaheadOutput(List<App.Bsky.Actor.ProfileViewBasic>? actors = default)
        {
            this.Actors = actors;
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="SearchActorsTypeaheadOutput"/> class.
        /// </summary>
        public SearchActorsTypeaheadOutput()
        {
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="SearchActorsTypeaheadOutput"/> class.
        /// </summary>
        public SearchActorsTypeaheadOutput(CBORObject obj)
        {
            if (obj["actors"] is not null) this.Actors = obj["actors"].Values.Select(n =>new App.Bsky.Actor.ProfileViewBasic(n)).ToList();
        }

        /// <summary>
        /// Gets or sets the actors.
        /// </summary>
        [JsonPropertyName("actors")]
        [JsonRequired]
        public List<App.Bsky.Actor.ProfileViewBasic>? Actors { get; set; }

        /// <summary>
        /// Gets the ATRecord Type.
        /// </summary>
        [JsonPropertyName("$type")]
        public override string Type => "app.bsky.actor.searchActorsTypeahead#SearchActorsTypeaheadOutput";

        public const string RecordType = "app.bsky.actor.searchActorsTypeahead#SearchActorsTypeaheadOutput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize<App.Bsky.Actor.SearchActorsTypeaheadOutput>(this, (JsonTypeInfo<App.Bsky.Actor.SearchActorsTypeaheadOutput>)SourceGenerationContext.Default.AppBskyActorSearchActorsTypeaheadOutput)!;
        }

        public static SearchActorsTypeaheadOutput FromJson(string json)
        {
            return JsonSerializer.Deserialize<App.Bsky.Actor.SearchActorsTypeaheadOutput>(json, (JsonTypeInfo<App.Bsky.Actor.SearchActorsTypeaheadOutput>)SourceGenerationContext.Default.AppBskyActorSearchActorsTypeaheadOutput)!;
        }
    }
}

