// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable

namespace FishyFlip.Lexicon.App.Bsky.Graph
{
    /// <summary>
    /// Record representing a block relationship against an entire an entire list of accounts (actors).
    /// </summary>
    public partial class Listblock : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="Listblock"/> class.
        /// </summary>
        public Listblock(FishyFlip.Models.ATUri? subject, DateTime? createdAt = default)
        {
            this.Subject = subject;
            this.CreatedAt = createdAt ?? DateTime.UtcNow;
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="Listblock"/> class.
        /// </summary>
        public Listblock()
        {
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="Listblock"/> class.
        /// </summary>
        public Listblock(CBORObject obj)
        {
            if (obj["subject"] is not null) this.Subject = obj["subject"].ToATUri();
            if (obj["createdAt"] is not null) this.CreatedAt = obj["createdAt"].ToDateTime();
        }

        /// <summary>
        /// Reference (AT-URI) to the mod list record.
        /// </summary>
        [JsonPropertyName("subject")]
        [JsonConverter(typeof(FishyFlip.Tools.Json.ATUriJsonConverter))]
        public FishyFlip.Models.ATUri? Subject { get; set; }

        [JsonPropertyName("createdAt")]
        public DateTime? CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Gets the ATRecord Type.
        /// </summary>
        [JsonPropertyName("$type")]
        public override string Type => "app.bsky.graph.listblock";

        public const string RecordType = "app.bsky.graph.listblock";

        public override string ToJson()
        {
            return JsonSerializer.Serialize<App.Bsky.Graph.Listblock>(this, (JsonTypeInfo<App.Bsky.Graph.Listblock>)SourceGenerationContext.Default.AppBskyGraphListblock)!;
        }

        public static Listblock FromJson(string json)
        {
            return JsonSerializer.Deserialize<App.Bsky.Graph.Listblock>(json, (JsonTypeInfo<App.Bsky.Graph.Listblock>)SourceGenerationContext.Default.AppBskyGraphListblock)!;
        }
    }
}

