// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Xrpc.Lexicon.App.Bsky.Video
{

    /// <summary>
    /// app.bsky.video XRPC Group.
    /// </summary>
    [ApiController]
    public abstract class VideoController : ControllerBase
    {

        /// <summary>
        /// Get status details for a video processing job.
        /// </summary>
        /// <param name="jobId"></param>
        /// <param name="cancellationToken"></param>
        /// <returns>Result of <see cref="FishyFlip.Lexicon.App.Bsky.Video.GetJobStatusOutput"/></returns>
        [HttpGet("/xrpc/app.bsky.video.getJobStatus")]
        public abstract Task<Results<ATResult<FishyFlip.Lexicon.App.Bsky.Video.GetJobStatusOutput>, ATErrorResult>> GetJobStatusAsync ([FromQuery] string jobId, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get video upload limits for the authenticated user.
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns>Result of <see cref="FishyFlip.Lexicon.App.Bsky.Video.GetUploadLimitsOutput"/></returns>
        [HttpGet("/xrpc/app.bsky.video.getUploadLimits")]
        public abstract Task<Results<ATResult<FishyFlip.Lexicon.App.Bsky.Video.GetUploadLimitsOutput>, ATErrorResult>> GetUploadLimitsAsync (CancellationToken cancellationToken = default);

        /// <summary>
        /// Upload a video to be processed then stored on the PDS.
        /// </summary>
        /// <param name="content"></param>
        /// <param name="cancellationToken"></param>
        /// <returns>Result of <see cref="FishyFlip.Lexicon.App.Bsky.Video.UploadVideoOutput"/></returns>
        [HttpPost("/xrpc/app.bsky.video.uploadVideo")]
        public abstract Task<Results<ATResult<FishyFlip.Lexicon.App.Bsky.Video.UploadVideoOutput>, ATErrorResult>> UploadVideoAsync ([FromBody] StreamContent content, CancellationToken cancellationToken = default);
    }
}

