// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Unspecced
{
    public partial class GetSuggestedUsersSkeletonOutput : ATObject, ICBOREncodable<GetSuggestedUsersSkeletonOutput>, IJsonEncodable<GetSuggestedUsersSkeletonOutput>, IParsable<GetSuggestedUsersSkeletonOutput>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="GetSuggestedUsersSkeletonOutput"/> class.
        /// </summary>
        /// <param name="dids"></param>
        public GetSuggestedUsersSkeletonOutput(List<FishyFlip.Models.ATDid> dids = default)
        {
            this.Dids = dids;
            this.Type = "app.bsky.unspecced.getSuggestedUsersSkeleton#GetSuggestedUsersSkeletonOutput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="GetSuggestedUsersSkeletonOutput"/> class.
        /// </summary>
        public GetSuggestedUsersSkeletonOutput()
        {
            this.Type = "app.bsky.unspecced.getSuggestedUsersSkeleton#GetSuggestedUsersSkeletonOutput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="GetSuggestedUsersSkeletonOutput"/> class.
        /// </summary>
        public GetSuggestedUsersSkeletonOutput(CBORObject obj)
        {
            if (obj["dids"] is not null) this.Dids = obj["dids"].Values.Select(n =>n.ToATDid()!).ToList();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the dids.
        /// </summary>
        [JsonPropertyName("dids")]
        [JsonRequired]
        public List<FishyFlip.Models.ATDid> Dids { get; set; }

        public const string RecordType = "app.bsky.unspecced.getSuggestedUsersSkeleton#GetSuggestedUsersSkeletonOutput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Unspecced.GetSuggestedUsersSkeletonOutput>)SourceGenerationContext.Default.AppBskyUnspeccedGetSuggestedUsersSkeletonOutput);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Unspecced.GetSuggestedUsersSkeletonOutput>)SourceGenerationContext.Default.AppBskyUnspeccedGetSuggestedUsersSkeletonOutput);
        }

        public static new GetSuggestedUsersSkeletonOutput FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Unspecced.GetSuggestedUsersSkeletonOutput>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Unspecced.GetSuggestedUsersSkeletonOutput>)SourceGenerationContext.Default.AppBskyUnspeccedGetSuggestedUsersSkeletonOutput)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new GetSuggestedUsersSkeletonOutput FromCBORObject(CBORObject obj)
        {
            return new GetSuggestedUsersSkeletonOutput(obj);
        }

        /// <inheritdoc/>
        public static GetSuggestedUsersSkeletonOutput Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<GetSuggestedUsersSkeletonOutput>(s, (JsonTypeInfo<GetSuggestedUsersSkeletonOutput>)SourceGenerationContext.Default.AppBskyUnspeccedGetSuggestedUsersSkeletonOutput)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out GetSuggestedUsersSkeletonOutput result)
        {
            result = JsonSerializer.Deserialize<GetSuggestedUsersSkeletonOutput>(s, (JsonTypeInfo<GetSuggestedUsersSkeletonOutput>)SourceGenerationContext.Default.AppBskyUnspeccedGetSuggestedUsersSkeletonOutput);
            return result != null;
        }
    }
}

