// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Blue.Moji.Packs
{
    /// <summary>
    /// Record representing a Bluemoji's inclusion in a specific pack. The AppView will ignore duplicate item records.
    /// </summary>
    public partial class Packitem : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="Packitem"/> class.
        /// </summary>
        /// <param name="subject">Reference (AT-URI) to the Bluemoji item record (blue.moji.collection.item).</param>
        /// <param name="pack">Reference (AT-URI) to the pack record (blue.moji.packs.pack).</param>
        /// <param name="createdAt"></param>
        public Packitem(FishyFlip.Models.ATUri? subject, FishyFlip.Models.ATUri? pack, DateTime? createdAt = default)
        {
            this.Subject = subject;
            this.Pack = pack;
            this.CreatedAt = createdAt ?? DateTime.UtcNow;
            this.Type = "blue.moji.packs.packitem";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="Packitem"/> class.
        /// </summary>
        public Packitem()
        {
            this.Type = "blue.moji.packs.packitem";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="Packitem"/> class.
        /// </summary>
        public Packitem(CBORObject obj)
        {
            if (obj["subject"] is not null) this.Subject = obj["subject"].ToATUri();
            if (obj["pack"] is not null) this.Pack = obj["pack"].ToATUri();
            if (obj["createdAt"] is not null) this.CreatedAt = obj["createdAt"].ToDateTime();
        }

        /// <summary>
        /// Gets or sets the subject.
        /// <br/> Reference (AT-URI) to the Bluemoji item record (blue.moji.collection.item).
        /// </summary>
        [JsonPropertyName("subject")]
        [JsonConverter(typeof(FishyFlip.Tools.Json.ATUriJsonConverter))]
        public FishyFlip.Models.ATUri? Subject { get; set; }

        /// <summary>
        /// Gets or sets the pack.
        /// <br/> Reference (AT-URI) to the pack record (blue.moji.packs.pack).
        /// </summary>
        [JsonPropertyName("pack")]
        [JsonConverter(typeof(FishyFlip.Tools.Json.ATUriJsonConverter))]
        public FishyFlip.Models.ATUri? Pack { get; set; }

        /// <summary>
        /// Gets or sets the createdAt.
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTime? CreatedAt { get; set; } = DateTime.UtcNow;

        public const string RecordType = "blue.moji.packs.packitem";

        public static Packitem FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.Blue.Moji.Packs.Packitem>(json, (JsonTypeInfo<FishyFlip.Lexicon.Blue.Moji.Packs.Packitem>)SourceGenerationContext.Default.BlueMojiPacksPackitem)!;
        }
    }
}

