// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

using FishyFlip.Lexicon.Com.Atproto.Repo;

namespace FishyFlip.Lexicon
{

    /// <summary>
    /// Extension methods for blue.moji.packs.
    /// </summary>
    public static class BlueMojiPacksExtensions
    {

        /// <summary>
        /// Create a Pack record.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="record"></param>
        /// <param name="rkey"></param>
        /// <param name="validate"></param>
        /// <param name="swapCommit"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<CreateRecordOutput?>> CreatePackAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, FishyFlip.Lexicon.Blue.Moji.Packs.Pack record, string? rkey = default, bool? validate = default, string? swapCommit = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.CreateRecordAsync(atp.ATProtocol.SessionManager.Session?.Did ?? throw new InvalidOperationException("Session did is required."), "blue.moji.packs.pack", record, rkey, validate, swapCommit, cancellationToken);
        }

        /// <summary>
        /// Create a Pack record.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="name"></param>
        /// <param name="description"></param>
        /// <param name="descriptionFacets"></param>
        /// <param name="icon"></param>
        /// <param name="adultOnly"></param>
        /// <param name="createdAt"></param>
        /// <param name="labels">Self-label values for this emoji. Effectively content warnings.
        /// <br/> Union Types: <br/>
        /// com.atproto.label.defs#selfLabels <br/>
        /// </param>
        /// <param name="rkey"></param>
        /// <param name="validate"></param>
        /// <param name="swapCommit"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<CreateRecordOutput?>> CreatePackAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, string? name, string? description = default, List<FishyFlip.Lexicon.Blue.Moji.Richtext.Facet>? descriptionFacets = default, Blob? icon = default, bool? adultOnly = default, DateTime? createdAt = default, FishyFlip.Lexicon.Com.Atproto.Label.SelfLabels? labels = default, string? rkey = default, bool? validate = default, string? swapCommit = default, CancellationToken cancellationToken = default)
        {
            var record = new FishyFlip.Lexicon.Blue.Moji.Packs.Pack();
            record.Name = name;
            record.Description = description;
            record.DescriptionFacets = descriptionFacets;
            record.Icon = icon;
            record.AdultOnly = adultOnly;
            record.CreatedAt = createdAt ?? DateTime.UtcNow;
            record.Labels = labels;
            return atp.ATProtocol.CreateRecordAsync(atp.ATProtocol.SessionManager.Session?.Did ?? throw new InvalidOperationException("Session did is required."), "blue.moji.packs.pack", record, rkey, validate, swapCommit, cancellationToken);
        }

        /// <summary>
        /// Delete a Pack record.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="rkey"></param>
        /// <param name="swapRecord"></param>
        /// <param name="swapCommit"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<DeleteRecordOutput?>> DeletePackAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, string rkey, string? swapRecord = default, string? swapCommit = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.DeleteRecordAsync(atp.ATProtocol.SessionManager.Session?.Did ?? throw new InvalidOperationException("Session did is required."), "blue.moji.packs.pack", rkey, swapRecord, swapCommit, cancellationToken);
        }

        /// <summary>
        /// Put a Pack record.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="rkey"></param>
        /// <param name="record"></param>
        /// <param name="validate"></param>
        /// <param name="swapRecord"></param>
        /// <param name="swapCommit"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<PutRecordOutput?>> PutPackAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, string rkey, FishyFlip.Lexicon.Blue.Moji.Packs.Pack record, bool? validate = default, string? swapRecord = default, string? swapCommit = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.PutRecordAsync(atp.ATProtocol.SessionManager.Session?.Did ?? throw new InvalidOperationException("Session did is required."), "blue.moji.packs.pack", rkey, record, validate, swapRecord, swapCommit, cancellationToken);
        }

        /// <summary>
        /// List Pack records.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="limit"></param>
        /// <param name="cursor"></param>
        /// <param name="reverse"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<ListRecordsOutput?>> ListPackAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, int? limit = 50, string? cursor = default, bool? reverse = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.ListRecordsAsync(atp.ATProtocol.SessionManager.Session?.Did ?? throw new InvalidOperationException("Session did is required."), "blue.moji.packs.pack", limit, cursor, reverse, cancellationToken);
        }

        /// <summary>
        /// List Pack records.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="repo"></param>
        /// <param name="limit"></param>
        /// <param name="cursor"></param>
        /// <param name="reverse"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<ListRecordsOutput?>> ListPackAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, FishyFlip.Models.ATIdentifier repo, int? limit = 50, string? cursor = default, bool? reverse = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.ListRecordsAsync(repo, "blue.moji.packs.pack", limit, cursor, reverse, cancellationToken);
        }

        /// <summary>
        /// Get Pack records.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="rkey"></param>
        /// <param name="cid"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<GetRecordOutput?>> GetPackAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, string rkey, string? cid = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.GetRecordAsync(atp.ATProtocol.SessionManager.Session?.Did ?? throw new InvalidOperationException("Session did is required."), "blue.moji.packs.pack", rkey, cid, cancellationToken);
        }

        /// <summary>
        /// Get Pack records.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="repo"></param>
        /// <param name="rkey"></param>
        /// <param name="cid"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<GetRecordOutput?>> GetPackAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, FishyFlip.Models.ATIdentifier repo, string rkey, string? cid = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.GetRecordAsync(repo, "blue.moji.packs.pack", rkey, cid, cancellationToken);
        }
        /// <summary>
        /// Create a Packitem record.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="record"></param>
        /// <param name="rkey"></param>
        /// <param name="validate"></param>
        /// <param name="swapCommit"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<CreateRecordOutput?>> CreatePackitemAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, FishyFlip.Lexicon.Blue.Moji.Packs.Packitem record, string? rkey = default, bool? validate = default, string? swapCommit = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.CreateRecordAsync(atp.ATProtocol.SessionManager.Session?.Did ?? throw new InvalidOperationException("Session did is required."), "blue.moji.packs.packitem", record, rkey, validate, swapCommit, cancellationToken);
        }

        /// <summary>
        /// Create a Packitem record.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="subject">Reference (AT-URI) to the Bluemoji item record (blue.moji.collection.item).</param>
        /// <param name="pack">Reference (AT-URI) to the pack record (blue.moji.packs.pack).</param>
        /// <param name="createdAt"></param>
        /// <param name="rkey"></param>
        /// <param name="validate"></param>
        /// <param name="swapCommit"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<CreateRecordOutput?>> CreatePackitemAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, FishyFlip.Models.ATUri? subject, FishyFlip.Models.ATUri? pack, DateTime? createdAt = default, string? rkey = default, bool? validate = default, string? swapCommit = default, CancellationToken cancellationToken = default)
        {
            var record = new FishyFlip.Lexicon.Blue.Moji.Packs.Packitem();
            record.Subject = subject;
            record.Pack = pack;
            record.CreatedAt = createdAt ?? DateTime.UtcNow;
            return atp.ATProtocol.CreateRecordAsync(atp.ATProtocol.SessionManager.Session?.Did ?? throw new InvalidOperationException("Session did is required."), "blue.moji.packs.packitem", record, rkey, validate, swapCommit, cancellationToken);
        }

        /// <summary>
        /// Delete a Packitem record.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="rkey"></param>
        /// <param name="swapRecord"></param>
        /// <param name="swapCommit"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<DeleteRecordOutput?>> DeletePackitemAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, string rkey, string? swapRecord = default, string? swapCommit = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.DeleteRecordAsync(atp.ATProtocol.SessionManager.Session?.Did ?? throw new InvalidOperationException("Session did is required."), "blue.moji.packs.packitem", rkey, swapRecord, swapCommit, cancellationToken);
        }

        /// <summary>
        /// Put a Packitem record.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="rkey"></param>
        /// <param name="record"></param>
        /// <param name="validate"></param>
        /// <param name="swapRecord"></param>
        /// <param name="swapCommit"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<PutRecordOutput?>> PutPackitemAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, string rkey, FishyFlip.Lexicon.Blue.Moji.Packs.Packitem record, bool? validate = default, string? swapRecord = default, string? swapCommit = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.PutRecordAsync(atp.ATProtocol.SessionManager.Session?.Did ?? throw new InvalidOperationException("Session did is required."), "blue.moji.packs.packitem", rkey, record, validate, swapRecord, swapCommit, cancellationToken);
        }

        /// <summary>
        /// List Packitem records.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="limit"></param>
        /// <param name="cursor"></param>
        /// <param name="reverse"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<ListRecordsOutput?>> ListPackitemAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, int? limit = 50, string? cursor = default, bool? reverse = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.ListRecordsAsync(atp.ATProtocol.SessionManager.Session?.Did ?? throw new InvalidOperationException("Session did is required."), "blue.moji.packs.packitem", limit, cursor, reverse, cancellationToken);
        }

        /// <summary>
        /// List Packitem records.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="repo"></param>
        /// <param name="limit"></param>
        /// <param name="cursor"></param>
        /// <param name="reverse"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<ListRecordsOutput?>> ListPackitemAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, FishyFlip.Models.ATIdentifier repo, int? limit = 50, string? cursor = default, bool? reverse = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.ListRecordsAsync(repo, "blue.moji.packs.packitem", limit, cursor, reverse, cancellationToken);
        }

        /// <summary>
        /// Get Packitem records.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="rkey"></param>
        /// <param name="cid"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<GetRecordOutput?>> GetPackitemAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, string rkey, string? cid = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.GetRecordAsync(atp.ATProtocol.SessionManager.Session?.Did ?? throw new InvalidOperationException("Session did is required."), "blue.moji.packs.packitem", rkey, cid, cancellationToken);
        }

        /// <summary>
        /// Get Packitem records.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="repo"></param>
        /// <param name="rkey"></param>
        /// <param name="cid"></param>
        /// <param name="cancellationToken"></param>
        public static Task<Result<GetRecordOutput?>> GetPackitemAsync(this FishyFlip.Lexicon.Blue.Moji.Packs.BlueMojiPacks atp, FishyFlip.Models.ATIdentifier repo, string rkey, string? cid = default, CancellationToken cancellationToken = default)
        {
            return atp.ATProtocol.GetRecordAsync(repo, "blue.moji.packs.packitem", rkey, cid, cancellationToken);
        }
    }
}

