// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Contact
{
    /// <summary>
    /// Associates a profile with the positional index of the contact import input in the call to `app.bsky.contact.importContacts`, so clients can know which phone caused a particular match.
    /// </summary>
    public partial class MatchAndContactIndex : ATObject, ICBOREncodable<MatchAndContactIndex>, IJsonEncodable<MatchAndContactIndex>, IParsable<MatchAndContactIndex>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="MatchAndContactIndex"/> class.
        /// </summary>
        /// <param name="match">Profile of the matched user.
        /// <see cref="FishyFlip.Lexicon.App.Bsky.Actor.ProfileView"/> (app.bsky.actor.defs#profileView)
        /// </param>
        /// <param name="contactIndex">The index of this match in the import contact input.</param>
        public MatchAndContactIndex(FishyFlip.Lexicon.App.Bsky.Actor.ProfileView match = default, long contactIndex = default)
        {
            this.Match = match;
            this.ContactIndex = contactIndex;
            this.Type = "app.bsky.contact.defs#matchAndContactIndex";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="MatchAndContactIndex"/> class.
        /// </summary>
        public MatchAndContactIndex()
        {
            this.Type = "app.bsky.contact.defs#matchAndContactIndex";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="MatchAndContactIndex"/> class.
        /// </summary>
        public MatchAndContactIndex(CBORObject obj)
        {
            if (obj["match"] is not null) this.Match = new FishyFlip.Lexicon.App.Bsky.Actor.ProfileView(obj["match"]);
            if (obj["contactIndex"] is not null) this.ContactIndex = obj["contactIndex"].AsInt64Value();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the match.
        /// <br/> Profile of the matched user.
        /// <br/> <see cref="FishyFlip.Lexicon.App.Bsky.Actor.ProfileView"/> (app.bsky.actor.defs#profileView)
        /// </summary>
        [JsonPropertyName("match")]
        [JsonRequired]
        public FishyFlip.Lexicon.App.Bsky.Actor.ProfileView Match { get; set; }

        /// <summary>
        /// Gets or sets the contactIndex.
        /// <br/> The index of this match in the import contact input.
        /// </summary>
        [JsonPropertyName("contactIndex")]
        [JsonRequired]
        public long ContactIndex { get; set; }

        public const string RecordType = "app.bsky.contact.defs#matchAndContactIndex";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Contact.MatchAndContactIndex>)SourceGenerationContext.Default.AppBskyContactMatchAndContactIndex);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Contact.MatchAndContactIndex>)SourceGenerationContext.Default.AppBskyContactMatchAndContactIndex);
        }

        public static new MatchAndContactIndex FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Contact.MatchAndContactIndex>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Contact.MatchAndContactIndex>)SourceGenerationContext.Default.AppBskyContactMatchAndContactIndex)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new MatchAndContactIndex FromCBORObject(CBORObject obj)
        {
            return new MatchAndContactIndex(obj);
        }

        /// <inheritdoc/>
        public static MatchAndContactIndex Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<MatchAndContactIndex>(s, (JsonTypeInfo<MatchAndContactIndex>)SourceGenerationContext.Default.AppBskyContactMatchAndContactIndex)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out MatchAndContactIndex result)
        {
            result = JsonSerializer.Deserialize<MatchAndContactIndex>(s, (JsonTypeInfo<MatchAndContactIndex>)SourceGenerationContext.Default.AppBskyContactMatchAndContactIndex);
            return result != null;
        }
    }
}

