// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Contact
{
    /// <summary>
    /// A stash object to be sent via bsync representing a notification to be created.
    /// </summary>
    public partial class Notification : ATObject, ICBOREncodable<Notification>, IJsonEncodable<Notification>, IParsable<Notification>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="Notification"/> class.
        /// </summary>
        /// <param name="from">The DID of who this notification comes from.</param>
        /// <param name="to">The DID of who this notification should go to.</param>
        public Notification(FishyFlip.Models.ATDid from = default, FishyFlip.Models.ATDid to = default)
        {
            this.From = from;
            this.To = to;
            this.Type = "app.bsky.contact.defs#notification";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="Notification"/> class.
        /// </summary>
        public Notification()
        {
            this.Type = "app.bsky.contact.defs#notification";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="Notification"/> class.
        /// </summary>
        public Notification(CBORObject obj)
        {
            if (obj["from"] is not null) this.From = obj["from"].ToATDid();
            if (obj["to"] is not null) this.To = obj["to"].ToATDid();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the from.
        /// <br/> The DID of who this notification comes from.
        /// </summary>
        [JsonPropertyName("from")]
        [JsonRequired]
        [JsonConverter(typeof(FishyFlip.Tools.Json.ATDidJsonConverter))]
        public FishyFlip.Models.ATDid From { get; set; }

        /// <summary>
        /// Gets or sets the to.
        /// <br/> The DID of who this notification should go to.
        /// </summary>
        [JsonPropertyName("to")]
        [JsonRequired]
        [JsonConverter(typeof(FishyFlip.Tools.Json.ATDidJsonConverter))]
        public FishyFlip.Models.ATDid To { get; set; }

        public const string RecordType = "app.bsky.contact.defs#notification";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Contact.Notification>)SourceGenerationContext.Default.AppBskyContactNotification);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Contact.Notification>)SourceGenerationContext.Default.AppBskyContactNotification);
        }

        public static new Notification FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Contact.Notification>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Contact.Notification>)SourceGenerationContext.Default.AppBskyContactNotification)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new Notification FromCBORObject(CBORObject obj)
        {
            return new Notification(obj);
        }

        /// <inheritdoc/>
        public static Notification Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<Notification>(s, (JsonTypeInfo<Notification>)SourceGenerationContext.Default.AppBskyContactNotification)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out Notification result)
        {
            result = JsonSerializer.Deserialize<Notification>(s, (JsonTypeInfo<Notification>)SourceGenerationContext.Default.AppBskyContactNotification);
            return result != null;
        }
    }
}

