// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Chat.Bsky.Convo
{
    public partial class LeaveConvoOutput : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="LeaveConvoOutput"/> class.
        /// </summary>
        /// <param name="convoId"></param>
        /// <param name="rev"></param>
        public LeaveConvoOutput(string convoId = default, string rev = default)
        {
            this.ConvoId = convoId;
            this.Rev = rev;
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="LeaveConvoOutput"/> class.
        /// </summary>
        public LeaveConvoOutput()
        {
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="LeaveConvoOutput"/> class.
        /// </summary>
        public LeaveConvoOutput(CBORObject obj)
        {
            if (obj["convoId"] is not null) this.ConvoId = obj["convoId"].AsString();
            if (obj["rev"] is not null) this.Rev = obj["rev"].AsString();
        }

        /// <summary>
        /// Gets or sets the convoId.
        /// </summary>
        [JsonPropertyName("convoId")]
        [JsonRequired]
        public string ConvoId { get; set; }

        /// <summary>
        /// Gets or sets the rev.
        /// </summary>
        [JsonPropertyName("rev")]
        [JsonRequired]
        public string Rev { get; set; }

        /// <summary>
        /// Gets the ATRecord Type.
        /// </summary>
        [JsonPropertyName("$type")]
        public override string Type => "chat.bsky.convo.leaveConvo#LeaveConvoOutput";

        public const string RecordType = "chat.bsky.convo.leaveConvo#LeaveConvoOutput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize<FishyFlip.Lexicon.Chat.Bsky.Convo.LeaveConvoOutput>(this, (JsonTypeInfo<FishyFlip.Lexicon.Chat.Bsky.Convo.LeaveConvoOutput>)SourceGenerationContext.Default.ChatBskyConvoLeaveConvoOutput)!;
        }

        public static LeaveConvoOutput FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.Chat.Bsky.Convo.LeaveConvoOutput>(json, (JsonTypeInfo<FishyFlip.Lexicon.Chat.Bsky.Convo.LeaveConvoOutput>)SourceGenerationContext.Default.ChatBskyConvoLeaveConvoOutput)!;
        }
    }
}

