// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Chat.Bsky.Convo
{
    public partial class LogUnmuteConvo : ATObject, ICBOREncodable<LogUnmuteConvo>, IJsonEncodable<LogUnmuteConvo>, IParsable<LogUnmuteConvo>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="LogUnmuteConvo"/> class.
        /// </summary>
        /// <param name="rev"></param>
        /// <param name="convoId"></param>
        public LogUnmuteConvo(string rev = default, string convoId = default)
        {
            this.Rev = rev;
            this.ConvoId = convoId;
            this.Type = "chat.bsky.convo.defs#logUnmuteConvo";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="LogUnmuteConvo"/> class.
        /// </summary>
        public LogUnmuteConvo()
        {
            this.Type = "chat.bsky.convo.defs#logUnmuteConvo";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="LogUnmuteConvo"/> class.
        /// </summary>
        public LogUnmuteConvo(CBORObject obj)
        {
            if (obj["rev"] is not null) this.Rev = obj["rev"].AsString();
            if (obj["convoId"] is not null) this.ConvoId = obj["convoId"].AsString();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the rev.
        /// </summary>
        [JsonPropertyName("rev")]
        [JsonRequired]
        public string Rev { get; set; }

        /// <summary>
        /// Gets or sets the convoId.
        /// </summary>
        [JsonPropertyName("convoId")]
        [JsonRequired]
        public string ConvoId { get; set; }

        public const string RecordType = "chat.bsky.convo.defs#logUnmuteConvo";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.Chat.Bsky.Convo.LogUnmuteConvo>)SourceGenerationContext.Default.ChatBskyConvoLogUnmuteConvo);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.Chat.Bsky.Convo.LogUnmuteConvo>)SourceGenerationContext.Default.ChatBskyConvoLogUnmuteConvo);
        }

        public static new LogUnmuteConvo FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.Chat.Bsky.Convo.LogUnmuteConvo>(json, (JsonTypeInfo<FishyFlip.Lexicon.Chat.Bsky.Convo.LogUnmuteConvo>)SourceGenerationContext.Default.ChatBskyConvoLogUnmuteConvo)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new LogUnmuteConvo FromCBORObject(CBORObject obj)
        {
            return new LogUnmuteConvo(obj);
        }

        /// <inheritdoc/>
        public static LogUnmuteConvo Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<LogUnmuteConvo>(s, (JsonTypeInfo<LogUnmuteConvo>)SourceGenerationContext.Default.ChatBskyConvoLogUnmuteConvo)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out LogUnmuteConvo result)
        {
            result = JsonSerializer.Deserialize<LogUnmuteConvo>(s, (JsonTypeInfo<LogUnmuteConvo>)SourceGenerationContext.Default.ChatBskyConvoLogUnmuteConvo);
            return result != null;
        }
    }
}

