// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Chat.Bsky.Convo
{
    public partial class RemoveReactionOutput : ATObject, ICBOREncodable<RemoveReactionOutput>, IJsonEncodable<RemoveReactionOutput>, IParsable<RemoveReactionOutput>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveReactionOutput"/> class.
        /// </summary>
        /// <param name="message">
        /// <see cref="FishyFlip.Lexicon.Chat.Bsky.Convo.MessageView"/> (chat.bsky.convo.defs#messageView)
        /// </param>
        public RemoveReactionOutput(FishyFlip.Lexicon.Chat.Bsky.Convo.MessageView message = default)
        {
            this.Message = message;
            this.Type = "chat.bsky.convo.removeReaction#RemoveReactionOutput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveReactionOutput"/> class.
        /// </summary>
        public RemoveReactionOutput()
        {
            this.Type = "chat.bsky.convo.removeReaction#RemoveReactionOutput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveReactionOutput"/> class.
        /// </summary>
        public RemoveReactionOutput(CBORObject obj)
        {
            if (obj["message"] is not null) this.Message = new FishyFlip.Lexicon.Chat.Bsky.Convo.MessageView(obj["message"]);
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the message.
        /// <br/> <see cref="FishyFlip.Lexicon.Chat.Bsky.Convo.MessageView"/> (chat.bsky.convo.defs#messageView)
        /// </summary>
        [JsonPropertyName("message")]
        [JsonRequired]
        public FishyFlip.Lexicon.Chat.Bsky.Convo.MessageView Message { get; set; }

        public const string RecordType = "chat.bsky.convo.removeReaction#RemoveReactionOutput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.Chat.Bsky.Convo.RemoveReactionOutput>)SourceGenerationContext.Default.ChatBskyConvoRemoveReactionOutput);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.Chat.Bsky.Convo.RemoveReactionOutput>)SourceGenerationContext.Default.ChatBskyConvoRemoveReactionOutput);
        }

        public static new RemoveReactionOutput FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.Chat.Bsky.Convo.RemoveReactionOutput>(json, (JsonTypeInfo<FishyFlip.Lexicon.Chat.Bsky.Convo.RemoveReactionOutput>)SourceGenerationContext.Default.ChatBskyConvoRemoveReactionOutput)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new RemoveReactionOutput FromCBORObject(CBORObject obj)
        {
            return new RemoveReactionOutput(obj);
        }

        /// <inheritdoc/>
        public static RemoveReactionOutput Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<RemoveReactionOutput>(s, (JsonTypeInfo<RemoveReactionOutput>)SourceGenerationContext.Default.ChatBskyConvoRemoveReactionOutput)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out RemoveReactionOutput result)
        {
            result = JsonSerializer.Deserialize<RemoveReactionOutput>(s, (JsonTypeInfo<RemoveReactionOutput>)SourceGenerationContext.Default.ChatBskyConvoRemoveReactionOutput);
            return result != null;
        }
    }
}

