// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable

namespace FishyFlip.Lexicon.App.Bsky.Notification
{
    public partial class RegisterPushInput : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterPushInput"/> class.
        /// </summary>
        public RegisterPushInput(FishyFlip.Models.ATDid? serviceDid = default, string? token = default, string? platform = default, string? appId = default)
        {
            this.ServiceDid = serviceDid;
            this.Token = token;
            this.Platform = platform;
            this.AppId = appId;
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterPushInput"/> class.
        /// </summary>
        public RegisterPushInput()
        {
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterPushInput"/> class.
        /// </summary>
        public RegisterPushInput(CBORObject obj)
        {
            if (obj["serviceDid"] is not null) this.ServiceDid = obj["serviceDid"].ToATDid();
            if (obj["token"] is not null) this.Token = obj["token"].AsString();
            // enum
            if (obj["appId"] is not null) this.AppId = obj["appId"].AsString();
        }

        [JsonPropertyName("serviceDid")]
        [JsonRequired]
        [JsonConverter(typeof(FishyFlip.Tools.Json.ATDidJsonConverter))]
        public FishyFlip.Models.ATDid? ServiceDid { get; set; }

        [JsonPropertyName("token")]
        [JsonRequired]
        public string? Token { get; set; }

        [JsonPropertyName("platform")]
        [JsonRequired]
        public string? Platform { get; set; }

        [JsonPropertyName("appId")]
        [JsonRequired]
        public string? AppId { get; set; }

        /// <summary>
        /// Gets the ATRecord Type.
        /// </summary>
        [JsonPropertyName("$type")]
        public override string Type => "app.bsky.notification.registerPush#RegisterPushInput";

        public const string RecordType = "app.bsky.notification.registerPush#RegisterPushInput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize<App.Bsky.Notification.RegisterPushInput>(this, (JsonTypeInfo<App.Bsky.Notification.RegisterPushInput>)SourceGenerationContext.Default.AppBskyNotificationRegisterPushInput)!;
        }

        public static RegisterPushInput FromJson(string json)
        {
            return JsonSerializer.Deserialize<App.Bsky.Notification.RegisterPushInput>(json, (JsonTypeInfo<App.Bsky.Notification.RegisterPushInput>)SourceGenerationContext.Default.AppBskyNotificationRegisterPushInput)!;
        }
    }
}

