// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Tools.Ozone.Moderation
{
    /// <summary>
    /// Unmute action on a subject
    /// </summary>
    public partial class ModEventUnmute : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="ModEventUnmute"/> class.
        /// </summary>
        /// <param name="comment">Describe reasoning behind the reversal.</param>
        public ModEventUnmute(string? comment = default)
        {
            this.Comment = comment;
            this.Type = "tools.ozone.moderation.defs#modEventUnmute";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="ModEventUnmute"/> class.
        /// </summary>
        public ModEventUnmute()
        {
            this.Type = "tools.ozone.moderation.defs#modEventUnmute";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="ModEventUnmute"/> class.
        /// </summary>
        public ModEventUnmute(CBORObject obj)
        {
            if (obj["comment"] is not null) this.Comment = obj["comment"].AsString();
        }

        /// <summary>
        /// Gets or sets the comment.
        /// <br/> Describe reasoning behind the reversal.
        /// </summary>
        [JsonPropertyName("comment")]
        public string? Comment { get; set; }

        public const string RecordType = "tools.ozone.moderation.defs#modEventUnmute";

        public override string ToJson()
        {
            return JsonSerializer.Serialize<FishyFlip.Lexicon.Tools.Ozone.Moderation.ModEventUnmute>(this, (JsonTypeInfo<FishyFlip.Lexicon.Tools.Ozone.Moderation.ModEventUnmute>)SourceGenerationContext.Default.ToolsOzoneModerationModEventUnmute)!;
        }

        public static ModEventUnmute FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.Tools.Ozone.Moderation.ModEventUnmute>(json, (JsonTypeInfo<FishyFlip.Lexicon.Tools.Ozone.Moderation.ModEventUnmute>)SourceGenerationContext.Default.ToolsOzoneModerationModEventUnmute)!;
        }
    }
}

