// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Tools.Ozone.Moderation
{
    public partial class RepoViewNotFound : ATObject, ICBOREncodable<RepoViewNotFound>, IJsonEncodable<RepoViewNotFound>, IParsable<RepoViewNotFound>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="RepoViewNotFound"/> class.
        /// </summary>
        /// <param name="did"></param>
        public RepoViewNotFound(FishyFlip.Models.ATDid did = default)
        {
            this.Did = did;
            this.Type = "tools.ozone.moderation.defs#repoViewNotFound";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="RepoViewNotFound"/> class.
        /// </summary>
        public RepoViewNotFound()
        {
            this.Type = "tools.ozone.moderation.defs#repoViewNotFound";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="RepoViewNotFound"/> class.
        /// </summary>
        public RepoViewNotFound(CBORObject obj)
        {
            if (obj["did"] is not null) this.Did = obj["did"].ToATDid();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the did.
        /// </summary>
        [JsonPropertyName("did")]
        [JsonRequired]
        [JsonConverter(typeof(FishyFlip.Tools.Json.ATDidJsonConverter))]
        public FishyFlip.Models.ATDid Did { get; set; }

        public const string RecordType = "tools.ozone.moderation.defs#repoViewNotFound";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.Tools.Ozone.Moderation.RepoViewNotFound>)SourceGenerationContext.Default.ToolsOzoneModerationRepoViewNotFound);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.Tools.Ozone.Moderation.RepoViewNotFound>)SourceGenerationContext.Default.ToolsOzoneModerationRepoViewNotFound);
        }

        public static new RepoViewNotFound FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.Tools.Ozone.Moderation.RepoViewNotFound>(json, (JsonTypeInfo<FishyFlip.Lexicon.Tools.Ozone.Moderation.RepoViewNotFound>)SourceGenerationContext.Default.ToolsOzoneModerationRepoViewNotFound)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new RepoViewNotFound FromCBORObject(CBORObject obj)
        {
            return new RepoViewNotFound(obj);
        }

        /// <inheritdoc/>
        public static RepoViewNotFound Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<RepoViewNotFound>(s, (JsonTypeInfo<RepoViewNotFound>)SourceGenerationContext.Default.ToolsOzoneModerationRepoViewNotFound)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out RepoViewNotFound result)
        {
            result = JsonSerializer.Deserialize<RepoViewNotFound>(s, (JsonTypeInfo<RepoViewNotFound>)SourceGenerationContext.Default.ToolsOzoneModerationRepoViewNotFound);
            return result != null;
        }
    }
}

