// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Tools.Ozone.Verification
{
    /// <summary>
    /// ListVerificationsOutput Collection.
    /// </summary>
    public class ListVerificationsOutputCollection : ATObjectCollectionBase<FishyFlip.Lexicon.Tools.Ozone.Verification.VerificationView>, IAsyncEnumerable<FishyFlip.Lexicon.Tools.Ozone.Verification.VerificationView>
    {

        public ListVerificationsOutputCollection(FishyFlip.ATProtocol atp, string? cursor = default, int? limit = 50, DateTime? createdAfter = default, DateTime? createdBefore = default, List<FishyFlip.Models.ATDid>? issuers = default, List<FishyFlip.Models.ATDid>? subjects = default, string? sortDirection = default, bool? isRevoked = default, CancellationToken cancellationToken = default)
             : base(atp)
        {
            this.Cursor = cursor;
            this.Limit = limit;
            this.CreatedAfter = createdAfter;
            this.CreatedBefore = createdBefore;
            this.Issuers = issuers;
            this.Subjects = subjects;
            this.SortDirection = sortDirection;
            this.IsRevoked = isRevoked;
            this.CancellationToken = cancellationToken;
        }

        public DateTime? CreatedAfter { get; }

        public DateTime? CreatedBefore { get; }

        public List<FishyFlip.Models.ATDid>? Issuers { get; }

        public List<FishyFlip.Models.ATDid>? Subjects { get; }

        public string? SortDirection { get; }

        public bool? IsRevoked { get; }

        /// <inheritdoc/>
        public override async Task<(IList<FishyFlip.Lexicon.Tools.Ozone.Verification.VerificationView> Posts, string Cursor)> GetRecordsAsync(int? limit = null, CancellationToken? token = default)
        {
            token = token ?? this.CancellationToken ?? System.Threading.CancellationToken.None;
            var (result, error) = await this.ATProtocol.ListVerificationsAsync(createdAfter: this.CreatedAfter, createdBefore: this.CreatedBefore, issuers: this.Issuers, subjects: this.Subjects, sortDirection: this.SortDirection, isRevoked: this.IsRevoked, limit: limit, cursor: this.Cursor, cancellationToken: token.Value!);

            this.HandleATError(error);

            if (result == null || result.Verifications == null)
            {
                throw new InvalidOperationException("The result or its properties cannot be null.");
            }

            return (result.Verifications, result.Cursor ?? string.Empty);
        }

        public static ListVerificationsOutputCollection Create(FishyFlip.ATProtocol atp, string? cursor = default, int? limit = 50, DateTime? createdAfter = default, DateTime? createdBefore = default, List<FishyFlip.Models.ATDid>? issuers = default, List<FishyFlip.Models.ATDid>? subjects = default, string? sortDirection = default, bool? isRevoked = default, CancellationToken cancellationToken = default)
        {
            return new(atp: atp, createdAfter: createdAfter, createdBefore: createdBefore, issuers: issuers, subjects: subjects, sortDirection: sortDirection, isRevoked: isRevoked, limit: limit, cursor: cursor, cancellationToken: cancellationToken);
        }
    }
}

