// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Com.Germnetwork
{
    public partial class MessageMe : ATObject, ICBOREncodable<MessageMe>, IJsonEncodable<MessageMe>, IParsable<MessageMe>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="MessageMe"/> class.
        /// </summary>
        /// <param name="messageMeUrl">A URL to present to an account that does not have its own com.germnetwork.declaration record, must have an empty fragment component, where the app should fill in the fragment component with the DIDs of the two accounts who wish to message each other</param>
        /// <param name="showButtonTo">The policy of who can message the account, this value is included in the keyPackage, but is duplicated here to allow applications to decide if they should show a 'Message on Germ' button to the viewer.
        /// <br/> Known Values: <br/>
        /// none <br/>
        /// usersIFollow <br/>
        /// everyone <br/>
        /// </param>
        public MessageMe(string messageMeUrl = default, string showButtonTo = default)
        {
            this.MessageMeUrl = messageMeUrl;
            this.ShowButtonTo = showButtonTo;
            this.Type = "com.germnetwork.declaration#messageMe";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="MessageMe"/> class.
        /// </summary>
        public MessageMe()
        {
            this.Type = "com.germnetwork.declaration#messageMe";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="MessageMe"/> class.
        /// </summary>
        public MessageMe(CBORObject obj)
        {
            if (obj["messageMeUrl"] is not null) this.MessageMeUrl = obj["messageMeUrl"].AsString();
            if (obj["showButtonTo"] is not null) this.ShowButtonTo = obj["showButtonTo"].AsString();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the messageMeUrl.
        /// <br/> A URL to present to an account that does not have its own com.germnetwork.declaration record, must have an empty fragment component, where the app should fill in the fragment component with the DIDs of the two accounts who wish to message each other
        /// </summary>
        [JsonPropertyName("messageMeUrl")]
        [JsonRequired]
        public string MessageMeUrl { get; set; }

        /// <summary>
        /// Gets or sets the showButtonTo.
        /// <br/> The policy of who can message the account, this value is included in the keyPackage, but is duplicated here to allow applications to decide if they should show a 'Message on Germ' button to the viewer.
        /// <br/> Known Values: <br/>
        /// none <br/>
        /// usersIFollow <br/>
        /// everyone <br/>
        /// </summary>
        [JsonPropertyName("showButtonTo")]
        [JsonRequired]
        public string ShowButtonTo { get; set; }

        public const string RecordType = "com.germnetwork.declaration#messageMe";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.Com.Germnetwork.MessageMe>)SourceGenerationContext.Default.ComGermnetworkMessageMe);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.Com.Germnetwork.MessageMe>)SourceGenerationContext.Default.ComGermnetworkMessageMe);
        }

        public static new MessageMe FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.Com.Germnetwork.MessageMe>(json, (JsonTypeInfo<FishyFlip.Lexicon.Com.Germnetwork.MessageMe>)SourceGenerationContext.Default.ComGermnetworkMessageMe)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new MessageMe FromCBORObject(CBORObject obj)
        {
            return new MessageMe(obj);
        }

        /// <inheritdoc/>
        public static MessageMe Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<MessageMe>(s, (JsonTypeInfo<MessageMe>)SourceGenerationContext.Default.ComGermnetworkMessageMe)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out MessageMe result)
        {
            result = JsonSerializer.Deserialize<MessageMe>(s, (JsonTypeInfo<MessageMe>)SourceGenerationContext.Default.ComGermnetworkMessageMe);
            return result != null;
        }
    }
}

