// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Tools.Ozone.Set
{

    /// <summary>
    /// tools.ozone.set Endpoint Group.
    /// </summary>
    public static class SetEndpoints
    {

       public const string GroupNamespace = "tools.ozone.set";

       public const string AddValues = "/xrpc/tools.ozone.set.addValues";

       public const string DeleteSet = "/xrpc/tools.ozone.set.deleteSet";

       public const string DeleteValues = "/xrpc/tools.ozone.set.deleteValues";

       public const string GetValues = "/xrpc/tools.ozone.set.getValues";

       public const string QuerySets = "/xrpc/tools.ozone.set.querySets";

       public const string UpsertSet = "/xrpc/tools.ozone.set.upsertSet";


        /// <summary>
        /// Add values to a specific set. Attempting to add values to a set that does not exist will result in an error.
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="name">Name of the set to add values to</param>
        /// <param name="values">Array of string values to add to the set</param>
        /// <param name="cancellationToken"></param>
        /// <returns>Result of <see cref="Success?"/></returns>
        public static Task<Result<Success?>> AddValuesAsync (this FishyFlip.IXrpcClient atp, string name, List<string> values, CancellationToken cancellationToken = default)
        {
            var endpointUrl = AddValues.ToString();
            var headers = new Dictionary<string, string>();
            headers.Add(Constants.AtProtoProxy, atp.OzoneProxyHeader);
            var inputItem = new AddValuesInput();
            inputItem.Name = name;
            inputItem.Values = values;
            return atp.ProcedureAsync<AddValuesInput, Success?>(endpointUrl, SourceGenerationContext.Default.ToolsOzoneSetAddValuesInput!, SourceGenerationContext.Default.Success!, inputItem, cancellationToken, headers);
        }


        /// <summary>
        /// Delete an entire set. Attempting to delete a set that does not exist will result in an error.
        /// <br/> Possible Errors: <br/>
        /// <see cref="FishyFlip.Lexicon.SetNotFoundError"/> set with the given name does not exist <br/>
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="name">Name of the set to delete</param>
        /// <param name="cancellationToken"></param>
        /// <returns>Result of <see cref="FishyFlip.Lexicon.Tools.Ozone.Set.DeleteSetOutput?"/></returns>
        public static Task<Result<FishyFlip.Lexicon.Tools.Ozone.Set.DeleteSetOutput?>> DeleteSetAsync (this FishyFlip.IXrpcClient atp, string name, CancellationToken cancellationToken = default)
        {
            var endpointUrl = DeleteSet.ToString();
            var headers = new Dictionary<string, string>();
            headers.Add(Constants.AtProtoProxy, atp.OzoneProxyHeader);
            var inputItem = new DeleteSetInput();
            inputItem.Name = name;
            return atp.ProcedureAsync<DeleteSetInput, FishyFlip.Lexicon.Tools.Ozone.Set.DeleteSetOutput?>(endpointUrl, SourceGenerationContext.Default.ToolsOzoneSetDeleteSetInput!, SourceGenerationContext.Default.ToolsOzoneSetDeleteSetOutput!, inputItem, cancellationToken, headers);
        }


        /// <summary>
        /// Delete values from a specific set. Attempting to delete values that are not in the set will not result in an error
        /// <br/> Possible Errors: <br/>
        /// <see cref="FishyFlip.Lexicon.SetNotFoundError"/> set with the given name does not exist <br/>
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="name">Name of the set to delete values from</param>
        /// <param name="values">Array of string values to delete from the set</param>
        /// <param name="cancellationToken"></param>
        /// <returns>Result of <see cref="Success?"/></returns>
        public static Task<Result<Success?>> DeleteValuesAsync (this FishyFlip.IXrpcClient atp, string name, List<string> values, CancellationToken cancellationToken = default)
        {
            var endpointUrl = DeleteValues.ToString();
            var headers = new Dictionary<string, string>();
            headers.Add(Constants.AtProtoProxy, atp.OzoneProxyHeader);
            var inputItem = new DeleteValuesInput();
            inputItem.Name = name;
            inputItem.Values = values;
            return atp.ProcedureAsync<DeleteValuesInput, Success?>(endpointUrl, SourceGenerationContext.Default.ToolsOzoneSetDeleteValuesInput!, SourceGenerationContext.Default.Success!, inputItem, cancellationToken, headers);
        }


        /// <summary>
        /// Get a specific set and its values
        /// <br/> Possible Errors: <br/>
        /// <see cref="FishyFlip.Lexicon.SetNotFoundError"/> set with the given name does not exist <br/>
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="name"></param>
        /// <param name="limit"></param>
        /// <param name="cursor"></param>
        /// <param name="cancellationToken"></param>
        /// <returns>Result of <see cref="FishyFlip.Lexicon.Tools.Ozone.Set.GetValuesOutput?"/></returns>
        public static Task<Result<FishyFlip.Lexicon.Tools.Ozone.Set.GetValuesOutput?>> GetValuesAsync (this FishyFlip.IXrpcClient atp, string name, int? limit = 100, string? cursor = default, CancellationToken cancellationToken = default)
        {
            var endpointUrl = GetValues.ToString();
            endpointUrl += "?";
            List<string> queryStrings = new();
            queryStrings.Add("name=" + name);

            if (limit != null)
            {
                queryStrings.Add("limit=" + limit);
            }

            if (cursor != null)
            {
                queryStrings.Add("cursor=" + cursor);
            }

            var headers = new Dictionary<string, string>();
            headers.Add(Constants.AtProtoProxy, atp.OzoneProxyHeader);
            headers.Add(Constants.AtProtoAcceptLabelers, string.Join(", ", atp.LabelParameters.Select(p => p.ToString())));
            endpointUrl += string.Join("&", queryStrings);
            return atp.QueryAsync<FishyFlip.Lexicon.Tools.Ozone.Set.GetValuesOutput>(endpointUrl, SourceGenerationContext.Default.ToolsOzoneSetGetValuesOutput!, cancellationToken, headers);
        }


        /// <summary>
        /// Query available sets
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="limit"></param>
        /// <param name="cursor"></param>
        /// <param name="namePrefix"></param>
        /// <param name="sortBy"></param>
        /// <param name="sortDirection">Defaults to ascending order of name field.</param>
        /// <param name="cancellationToken"></param>
        /// <returns>Result of <see cref="FishyFlip.Lexicon.Tools.Ozone.Set.QuerySetsOutput?"/></returns>
        public static Task<Result<FishyFlip.Lexicon.Tools.Ozone.Set.QuerySetsOutput?>> QuerySetsAsync (this FishyFlip.IXrpcClient atp, int? limit = 50, string? cursor = default, string? namePrefix = default, string? sortBy = default, string? sortDirection = default, CancellationToken cancellationToken = default)
        {
            var endpointUrl = QuerySets.ToString();
            endpointUrl += "?";
            List<string> queryStrings = new();
            if (limit != null)
            {
                queryStrings.Add("limit=" + limit);
            }

            if (cursor != null)
            {
                queryStrings.Add("cursor=" + cursor);
            }

            if (namePrefix != null)
            {
                queryStrings.Add("namePrefix=" + namePrefix);
            }

            if (sortBy != null)
            {
                queryStrings.Add("sortBy=" + sortBy);
            }

            if (sortDirection != null)
            {
                queryStrings.Add("sortDirection=" + sortDirection);
            }

            var headers = new Dictionary<string, string>();
            headers.Add(Constants.AtProtoProxy, atp.OzoneProxyHeader);
            headers.Add(Constants.AtProtoAcceptLabelers, string.Join(", ", atp.LabelParameters.Select(p => p.ToString())));
            endpointUrl += string.Join("&", queryStrings);
            return atp.QueryAsync<FishyFlip.Lexicon.Tools.Ozone.Set.QuerySetsOutput>(endpointUrl, SourceGenerationContext.Default.ToolsOzoneSetQuerySetsOutput!, cancellationToken, headers);
        }


        /// <summary>
        /// Create or update set metadata
        /// </summary>
        /// <param name="atp"></param>
        /// <param name="Set"></param>
        /// <param name="cancellationToken"></param>
        /// <returns>Result of <see cref="FishyFlip.Lexicon.Tools.Ozone.Set.SetView?"/></returns>
        public static Task<Result<FishyFlip.Lexicon.Tools.Ozone.Set.SetView?>> UpsertSetAsync (this FishyFlip.IXrpcClient atp, FishyFlip.Lexicon.Tools.Ozone.Set.Set Set, CancellationToken cancellationToken = default)
        {
            var endpointUrl = UpsertSet.ToString();
            var headers = new Dictionary<string, string>();
            headers.Add(Constants.AtProtoProxy, atp.OzoneProxyHeader);
            var inputItem = new UpsertSetInput();
            inputItem.Set = Set;
            return atp.ProcedureAsync<UpsertSetInput, FishyFlip.Lexicon.Tools.Ozone.Set.SetView?>(endpointUrl, SourceGenerationContext.Default.ToolsOzoneSetUpsertSetInput!, SourceGenerationContext.Default.ToolsOzoneSetSetView!, inputItem, cancellationToken, headers);
        }

    }
}

