// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Com.Atproto.Identity
{
    public partial class SubmitPlcOperationInput : ATObject, ICBOREncodable<SubmitPlcOperationInput>, IJsonEncodable<SubmitPlcOperationInput>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitPlcOperationInput"/> class.
        /// </summary>
        /// <param name="operation"></param>
        public SubmitPlcOperationInput(ATObject operation = default)
        {
            this.Operation = operation;
            this.Type = "com.atproto.identity.submitPlcOperation#SubmitPlcOperationInput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitPlcOperationInput"/> class.
        /// </summary>
        public SubmitPlcOperationInput()
        {
            this.Type = "com.atproto.identity.submitPlcOperation#SubmitPlcOperationInput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitPlcOperationInput"/> class.
        /// </summary>
        public SubmitPlcOperationInput(CBORObject obj)
        {
            if (obj["operation"] is not null) this.Operation = obj["operation"].ToATObject();
        }

        /// <summary>
        /// Gets or sets the operation.
        /// </summary>
        [JsonPropertyName("operation")]
        [JsonRequired]
        public ATObject Operation { get; set; }

        public const string RecordType = "com.atproto.identity.submitPlcOperation#SubmitPlcOperationInput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.Com.Atproto.Identity.SubmitPlcOperationInput>)SourceGenerationContext.Default.ComAtprotoIdentitySubmitPlcOperationInput);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.Com.Atproto.Identity.SubmitPlcOperationInput>)SourceGenerationContext.Default.ComAtprotoIdentitySubmitPlcOperationInput);
        }

        public static new SubmitPlcOperationInput FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.Com.Atproto.Identity.SubmitPlcOperationInput>(json, (JsonTypeInfo<FishyFlip.Lexicon.Com.Atproto.Identity.SubmitPlcOperationInput>)SourceGenerationContext.Default.ComAtprotoIdentitySubmitPlcOperationInput)!;
        }

         /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

         /// <inheritdoc/>
        public static new SubmitPlcOperationInput FromCBORObject(CBORObject obj)
        {
            return new SubmitPlcOperationInput(obj);
        }

    }
}

