// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable

namespace FishyFlip.Lexicon.Chat.Bsky.Actor
{

    /// <summary>
    /// chat.bsky.actor Endpoint Group.
    /// </summary>
    public static class ActorEndpoints
    {

       public const string ExportAccountData = "/xrpc/chat.bsky.actor.exportAccountData";

       public const string DeleteAccount = "/xrpc/chat.bsky.actor.deleteAccount";


        /// <summary>
        /// Generated endpoint for chat.bsky.actor.exportAccountData
        /// </summary>
        public static Task<Result<Success?>> ExportAccountDataAsync (this FishyFlip.ATProtocol atp, CancellationToken cancellationToken = default)
        {
            var endpointUrl = ExportAccountData.ToString();
            return atp.Client.Get<Success>(endpointUrl, atp.Options.SourceGenerationContext.Success!, atp.Options.JsonSerializerOptions, cancellationToken, atp.Options.Logger);
        }


        /// <summary>
        /// Generated endpoint for chat.bsky.actor.deleteAccount
        /// </summary>
        public static Task<Result<FishyFlip.Lexicon.Chat.Bsky.Actor.DeleteAccountOutput?>> DeleteAccountAsync (this FishyFlip.ATProtocol atp, CancellationToken cancellationToken = default)
        {
            var endpointUrl = DeleteAccount.ToString();
            return atp.Client.Post<FishyFlip.Lexicon.Chat.Bsky.Actor.DeleteAccountOutput?>(endpointUrl, atp.Options.SourceGenerationContext.ChatBskyActorDeleteAccountOutput!, atp.Options.JsonSerializerOptions, cancellationToken, atp.Options.Logger);
        }

    }
}

