// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Com.Atproto.Admin
{
    public partial class GetInviteCodesOutput : ATObject, ICBOREncodable<GetInviteCodesOutput>, IJsonEncodable<GetInviteCodesOutput>, IParsable<GetInviteCodesOutput>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="GetInviteCodesOutput"/> class.
        /// </summary>
        /// <param name="cursor"></param>
        /// <param name="codes"></param>
        public GetInviteCodesOutput(string? cursor = default, List<FishyFlip.Lexicon.Com.Atproto.Server.InviteCode> codes = default)
        {
            this.Cursor = cursor;
            this.Codes = codes;
            this.Type = "com.atproto.admin.getInviteCodes#GetInviteCodesOutput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="GetInviteCodesOutput"/> class.
        /// </summary>
        public GetInviteCodesOutput()
        {
            this.Type = "com.atproto.admin.getInviteCodes#GetInviteCodesOutput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="GetInviteCodesOutput"/> class.
        /// </summary>
        public GetInviteCodesOutput(CBORObject obj)
        {
            if (obj["cursor"] is not null) this.Cursor = obj["cursor"].AsString();
            if (obj["codes"] is not null) this.Codes = obj["codes"].Values.Select(n =>new FishyFlip.Lexicon.Com.Atproto.Server.InviteCode(n)).ToList();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the cursor.
        /// </summary>
        [JsonPropertyName("cursor")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Cursor { get; set; }

        /// <summary>
        /// Gets or sets the codes.
        /// </summary>
        [JsonPropertyName("codes")]
        [JsonRequired]
        public List<FishyFlip.Lexicon.Com.Atproto.Server.InviteCode> Codes { get; set; }

        public const string RecordType = "com.atproto.admin.getInviteCodes#GetInviteCodesOutput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.Com.Atproto.Admin.GetInviteCodesOutput>)SourceGenerationContext.Default.ComAtprotoAdminGetInviteCodesOutput);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.Com.Atproto.Admin.GetInviteCodesOutput>)SourceGenerationContext.Default.ComAtprotoAdminGetInviteCodesOutput);
        }

        public static new GetInviteCodesOutput FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.Com.Atproto.Admin.GetInviteCodesOutput>(json, (JsonTypeInfo<FishyFlip.Lexicon.Com.Atproto.Admin.GetInviteCodesOutput>)SourceGenerationContext.Default.ComAtprotoAdminGetInviteCodesOutput)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new GetInviteCodesOutput FromCBORObject(CBORObject obj)
        {
            return new GetInviteCodesOutput(obj);
        }

        /// <inheritdoc/>
        public static GetInviteCodesOutput Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<GetInviteCodesOutput>(s, (JsonTypeInfo<GetInviteCodesOutput>)SourceGenerationContext.Default.ComAtprotoAdminGetInviteCodesOutput)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out GetInviteCodesOutput result)
        {
            result = JsonSerializer.Deserialize<GetInviteCodesOutput>(s, (JsonTypeInfo<GetInviteCodesOutput>)SourceGenerationContext.Default.ComAtprotoAdminGetInviteCodesOutput);
            return result != null;
        }
    }
}

