// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable

namespace FishyFlip.Lexicon.Com.Atproto.Server
{
    public partial class ResetPasswordInput : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="ResetPasswordInput"/> class.
        /// </summary>
        public ResetPasswordInput(string? token = default, string? password = default)
        {
            this.Token = token;
            this.Password = password;
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="ResetPasswordInput"/> class.
        /// </summary>
        public ResetPasswordInput()
        {
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="ResetPasswordInput"/> class.
        /// </summary>
        public ResetPasswordInput(CBORObject obj)
        {
            if (obj["token"] is not null) this.Token = obj["token"].AsString();
            if (obj["password"] is not null) this.Password = obj["password"].AsString();
        }

        [JsonPropertyName("token")]
        [JsonRequired]
        public string? Token { get; set; }

        [JsonPropertyName("password")]
        [JsonRequired]
        public string? Password { get; set; }

        /// <summary>
        /// Gets the ATRecord Type.
        /// </summary>
        [JsonPropertyName("$type")]
        public override string Type => "com.atproto.server.resetPassword#ResetPasswordInput";

        public const string RecordType = "com.atproto.server.resetPassword#ResetPasswordInput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize<Com.Atproto.Server.ResetPasswordInput>(this, (JsonTypeInfo<Com.Atproto.Server.ResetPasswordInput>)SourceGenerationContext.Default.ComAtprotoServerResetPasswordInput)!;
        }

        public static ResetPasswordInput FromJson(string json)
        {
            return JsonSerializer.Deserialize<Com.Atproto.Server.ResetPasswordInput>(json, (JsonTypeInfo<Com.Atproto.Server.ResetPasswordInput>)SourceGenerationContext.Default.ComAtprotoServerResetPasswordInput)!;
        }
    }
}

