// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Tools.Ozone.Safelink
{
    public partial class UpdateRuleInput : ATObject, ICBOREncodable<UpdateRuleInput>, IJsonEncodable<UpdateRuleInput>, IParsable<UpdateRuleInput>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRuleInput"/> class.
        /// </summary>
        /// <param name="url">The URL or domain to update the rule for</param>
        /// <param name="pattern">
        /// <br/> Known Values: <br/>
        /// domain <br/>
        /// url <br/>
        /// </param>
        /// <param name="action">
        /// <br/> Known Values: <br/>
        /// block <br/>
        /// warn <br/>
        /// whitelist <br/>
        /// </param>
        /// <param name="reason">
        /// <br/> Known Values: <br/>
        /// csam <br/>
        /// spam <br/>
        /// phishing <br/>
        /// none <br/>
        /// </param>
        /// <param name="comment">Optional comment about the update</param>
        /// <param name="createdBy">Optional DID to credit as the creator. Only respected for admin_token authentication.</param>
        public UpdateRuleInput(string url = default, string pattern = default, string action = default, string reason = default, string? comment = default, FishyFlip.Models.ATDid? createdBy = default)
        {
            this.Url = url;
            this.Pattern = pattern;
            this.Action = action;
            this.Reason = reason;
            this.Comment = comment;
            this.CreatedBy = createdBy;
            this.Type = "tools.ozone.safelink.updateRule#UpdateRuleInput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRuleInput"/> class.
        /// </summary>
        public UpdateRuleInput()
        {
            this.Type = "tools.ozone.safelink.updateRule#UpdateRuleInput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRuleInput"/> class.
        /// </summary>
        public UpdateRuleInput(CBORObject obj)
        {
            if (obj["url"] is not null) this.Url = obj["url"].AsString();
            if (obj["pattern"] is not null) this.Pattern = obj["pattern"].AsString();
            if (obj["action"] is not null) this.Action = obj["action"].AsString();
            if (obj["reason"] is not null) this.Reason = obj["reason"].AsString();
            if (obj["comment"] is not null) this.Comment = obj["comment"].AsString();
            if (obj["createdBy"] is not null) this.CreatedBy = obj["createdBy"].ToATDid();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the url.
        /// <br/> The URL or domain to update the rule for
        /// </summary>
        [JsonPropertyName("url")]
        [JsonRequired]
        public string Url { get; set; }

        /// <summary>
        /// Gets or sets the pattern.
        /// <br/> Known Values: <br/>
        /// domain <br/>
        /// url <br/>
        /// </summary>
        [JsonPropertyName("pattern")]
        [JsonRequired]
        public string Pattern { get; set; }

        /// <summary>
        /// Gets or sets the action.
        /// <br/> Known Values: <br/>
        /// block <br/>
        /// warn <br/>
        /// whitelist <br/>
        /// </summary>
        [JsonPropertyName("action")]
        [JsonRequired]
        public string Action { get; set; }

        /// <summary>
        /// Gets or sets the reason.
        /// <br/> Known Values: <br/>
        /// csam <br/>
        /// spam <br/>
        /// phishing <br/>
        /// none <br/>
        /// </summary>
        [JsonPropertyName("reason")]
        [JsonRequired]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or sets the comment.
        /// <br/> Optional comment about the update
        /// </summary>
        [JsonPropertyName("comment")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Comment { get; set; }

        /// <summary>
        /// Gets or sets the createdBy.
        /// <br/> Optional DID to credit as the creator. Only respected for admin_token authentication.
        /// </summary>
        [JsonPropertyName("createdBy")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonConverter(typeof(FishyFlip.Tools.Json.ATDidJsonConverter))]
        public FishyFlip.Models.ATDid? CreatedBy { get; set; }

        public const string RecordType = "tools.ozone.safelink.updateRule#UpdateRuleInput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.Tools.Ozone.Safelink.UpdateRuleInput>)SourceGenerationContext.Default.ToolsOzoneSafelinkUpdateRuleInput);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.Tools.Ozone.Safelink.UpdateRuleInput>)SourceGenerationContext.Default.ToolsOzoneSafelinkUpdateRuleInput);
        }

        public static new UpdateRuleInput FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.Tools.Ozone.Safelink.UpdateRuleInput>(json, (JsonTypeInfo<FishyFlip.Lexicon.Tools.Ozone.Safelink.UpdateRuleInput>)SourceGenerationContext.Default.ToolsOzoneSafelinkUpdateRuleInput)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new UpdateRuleInput FromCBORObject(CBORObject obj)
        {
            return new UpdateRuleInput(obj);
        }

        /// <inheritdoc/>
        public static UpdateRuleInput Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<UpdateRuleInput>(s, (JsonTypeInfo<UpdateRuleInput>)SourceGenerationContext.Default.ToolsOzoneSafelinkUpdateRuleInput)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out UpdateRuleInput result)
        {
            result = JsonSerializer.Deserialize<UpdateRuleInput>(s, (JsonTypeInfo<UpdateRuleInput>)SourceGenerationContext.Default.ToolsOzoneSafelinkUpdateRuleInput);
            return result != null;
        }
    }
}

