// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Com.Atproto.Repo
{
    /// <summary>
    /// Operation which deletes an existing record.
    /// </summary>
    public partial class Delete : ATObject, ICBOREncodable<Delete>, IJsonEncodable<Delete>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="Delete"/> class.
        /// </summary>
        /// <param name="collection"></param>
        /// <param name="rkey"></param>
        public Delete(string collection = default, string rkey = default)
        {
            this.Collection = collection;
            this.Rkey = rkey;
            this.Type = "com.atproto.repo.applyWrites#delete";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="Delete"/> class.
        /// </summary>
        public Delete()
        {
            this.Type = "com.atproto.repo.applyWrites#delete";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="Delete"/> class.
        /// </summary>
        public Delete(CBORObject obj)
        {
            if (obj["collection"] is not null) this.Collection = obj["collection"].AsString();
            if (obj["rkey"] is not null) this.Rkey = obj["rkey"].AsString();
        }

        /// <summary>
        /// Gets or sets the collection.
        /// </summary>
        [JsonPropertyName("collection")]
        [JsonRequired]
        public string Collection { get; set; }

        /// <summary>
        /// Gets or sets the rkey.
        /// </summary>
        [JsonPropertyName("rkey")]
        [JsonRequired]
        public string Rkey { get; set; }

        public const string RecordType = "com.atproto.repo.applyWrites#delete";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.Com.Atproto.Repo.Delete>)SourceGenerationContext.Default.ComAtprotoRepoDelete);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.Com.Atproto.Repo.Delete>)SourceGenerationContext.Default.ComAtprotoRepoDelete);
        }

        public static new Delete FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.Com.Atproto.Repo.Delete>(json, (JsonTypeInfo<FishyFlip.Lexicon.Com.Atproto.Repo.Delete>)SourceGenerationContext.Default.ComAtprotoRepoDelete)!;
        }

         /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

         /// <inheritdoc/>
        public static new Delete FromCBORObject(CBORObject obj)
        {
            return new Delete(obj);
        }

    }
}

