// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Com.Atproto.Repo
{
    /// <summary>
    /// ListMissingBlobsOutput Collection.
    /// </summary>
    public class ListMissingBlobsOutputCollection : ATObjectCollectionBase<FishyFlip.Lexicon.Com.Atproto.Repo.RecordBlob>, IAsyncEnumerable<FishyFlip.Lexicon.Com.Atproto.Repo.RecordBlob>
    {

        public ListMissingBlobsOutputCollection(FishyFlip.IXrpcClient atp, int? limit = 500, string? cursor = default, CancellationToken cancellationToken = default)
             : base(atp)
        {
            this.Limit = limit;
            this.Cursor = cursor;
            this.CancellationToken = cancellationToken;
        }

        /// <inheritdoc/>
        public override async Task<(IList<FishyFlip.Lexicon.Com.Atproto.Repo.RecordBlob> Posts, string Cursor)> GetRecordsAsync(int? limit = null, CancellationToken? token = default)
        {
            token = token ?? this.CancellationToken ?? System.Threading.CancellationToken.None;
            var (result, error) = await this.ATProtocol.ListMissingBlobsAsync(limit: limit, cursor: this.Cursor, cancellationToken: token.Value!);

            this.HandleATError(error);

            if (result == null || result.Blobs == null)
            {
                throw new InvalidOperationException("The result or its properties cannot be null.");
            }

            return (result.Blobs, result.Cursor ?? string.Empty);
        }

        public static ListMissingBlobsOutputCollection Create(FishyFlip.IXrpcClient atp, int? limit = 500, string? cursor = default, CancellationToken cancellationToken = default)
        {
            return new(atp: atp, limit: limit, cursor: cursor, cancellationToken: cancellationToken);
        }
    }
}

