// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.My.Skylights
{
    public partial class Item : ATObject, ICBOREncodable<Item>, IJsonEncodable<Item>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="Item"/> class.
        /// </summary>
        /// <param name="@ref"></param>
        /// <param name="value"></param>
        public Item(string @ref = default, string value = default)
        {
            this.Ref = @ref;
            this.Value = value;
            this.Type = "my.skylights.rel#item";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="Item"/> class.
        /// </summary>
        public Item()
        {
            this.Type = "my.skylights.rel#item";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="Item"/> class.
        /// </summary>
        public Item(CBORObject obj)
        {
            if (obj["ref"] is not null) this.Ref = obj["ref"].AsString();
            if (obj["value"] is not null) this.Value = obj["value"].AsString();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the ref.
        /// </summary>
        [JsonPropertyName("ref")]
        [JsonRequired]
        public string Ref { get; set; }

        /// <summary>
        /// Gets or sets the value.
        /// </summary>
        [JsonPropertyName("value")]
        [JsonRequired]
        public string Value { get; set; }

        public const string RecordType = "my.skylights.rel#item";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.My.Skylights.Item>)SourceGenerationContext.Default.MySkylightsItem);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.My.Skylights.Item>)SourceGenerationContext.Default.MySkylightsItem);
        }

        public static new Item FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.My.Skylights.Item>(json, (JsonTypeInfo<FishyFlip.Lexicon.My.Skylights.Item>)SourceGenerationContext.Default.MySkylightsItem)!;
        }

         /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

         /// <inheritdoc/>
        public static new Item FromCBORObject(CBORObject obj)
        {
            return new Item(obj);
        }

    }
}

