// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Tools.Ozone.Setting
{

    /// <summary>
    /// tools.ozone.setting Endpoint Class.
    /// </summary>
    public sealed class ToolsOzoneSetting
    {

        private IXrpcClient atp;

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsOzoneSetting"/> class.
        /// </summary>
        /// <param name="atp"><see cref="ATProtocol"/>.</param>
        internal ToolsOzoneSetting(IXrpcClient atp)
        {
            this.atp = atp;
        }

        /// <summary>
        /// Gets the ATProtocol.
        /// </summary>
        internal IXrpcClient ATProtocol => this.atp;


        /// <summary>
        /// List settings with optional filtering
        /// </summary>
        /// <param name="limit"></param>
        /// <param name="cursor"></param>
        /// <param name="scope"></param>
        /// <param name="prefix">Filter keys by prefix</param>
        /// <param name="keys">Filter for only the specified keys. Ignored if prefix is provided</param>
        /// <param name="cancellationToken"></param>
        public Task<Result<FishyFlip.Lexicon.Tools.Ozone.Setting.ListOptionsOutput?>> ListOptionsAsync (int? limit = 50, string? cursor = default, string? scope = default, string? prefix = default, List<string>? keys = default, CancellationToken cancellationToken = default)
        {
            return atp.ListOptionsAsync(limit, cursor, scope, prefix, keys, cancellationToken);
        }

        /// <summary>
        /// List settings with optional filtering
        /// </summary>
        /// <param name="limit"></param>
        /// <param name="cursor"></param>
        /// <param name="scope"></param>
        /// <param name="prefix">Filter keys by prefix</param>
        /// <param name="keys">Filter for only the specified keys. Ignored if prefix is provided</param>
        /// <param name="cancellationToken"></param>
        public ListOptionsOutputCollection ListOptionsCollectionAsync (int? limit = 50, string? cursor = default, string? scope = default, string? prefix = default, List<string>? keys = default, CancellationToken cancellationToken = default)
        {
            return new ListOptionsOutputCollection(atp, limit, cursor, scope, prefix, keys, cancellationToken);
        }


        /// <summary>
        /// Delete settings by key
        /// </summary>
        /// <param name="keys"></param>
        /// <param name="scope"></param>
        /// <param name="cancellationToken"></param>
        public Task<Result<FishyFlip.Lexicon.Tools.Ozone.Setting.RemoveOptionsOutput?>> RemoveOptionsAsync (List<string> keys, string scope, CancellationToken cancellationToken = default)
        {
            return atp.RemoveOptionsAsync(keys, scope, cancellationToken);
        }


        /// <summary>
        /// Create or update setting option
        /// </summary>
        /// <param name="key"></param>
        /// <param name="scope"></param>
        /// <param name="value"></param>
        /// <param name="description"></param>
        /// <param name="managerRole"></param>
        /// <param name="cancellationToken"></param>
        public Task<Result<FishyFlip.Lexicon.Tools.Ozone.Setting.UpsertOptionOutput?>> UpsertOptionAsync (string key, string scope, ATObject value, string? description = default, string? managerRole = default, CancellationToken cancellationToken = default)
        {
            return atp.UpsertOptionAsync(key, scope, value, description, managerRole, cancellationToken);
        }

    }
}

