// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Feed
{
    public partial class GetActorLikesOutput : ATObject, IBatchItem
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="GetActorLikesOutput"/> class.
        /// </summary>
        /// <param name="cursor"></param>
        /// <param name="feed"></param>
        public GetActorLikesOutput(string? cursor = default, List<FishyFlip.Lexicon.App.Bsky.Feed.FeedViewPost> feed = default)
        {
            this.Cursor = cursor;
            this.Feed = feed;
            this.Type = "app.bsky.feed.getActorLikes#GetActorLikesOutput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="GetActorLikesOutput"/> class.
        /// </summary>
        public GetActorLikesOutput()
        {
            this.Type = "app.bsky.feed.getActorLikes#GetActorLikesOutput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="GetActorLikesOutput"/> class.
        /// </summary>
        public GetActorLikesOutput(CBORObject obj)
        {
            if (obj["cursor"] is not null) this.Cursor = obj["cursor"].AsString();
            if (obj["feed"] is not null) this.Feed = obj["feed"].Values.Select(n =>new FishyFlip.Lexicon.App.Bsky.Feed.FeedViewPost(n)).ToList();
        }

        /// <summary>
        /// Gets or sets the cursor.
        /// </summary>
        [JsonPropertyName("cursor")]
        public string? Cursor { get; set; }

        /// <summary>
        /// Gets or sets the feed.
        /// </summary>
        [JsonPropertyName("feed")]
        [JsonRequired]
        public List<FishyFlip.Lexicon.App.Bsky.Feed.FeedViewPost> Feed { get; set; }

        public const string RecordType = "app.bsky.feed.getActorLikes#GetActorLikesOutput";

        public static GetActorLikesOutput FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Feed.GetActorLikesOutput>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Feed.GetActorLikesOutput>)SourceGenerationContext.Default.AppBskyFeedGetActorLikesOutput)!;
        }
    }
}

