// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Feed
{
    public partial class GetFeedGeneratorsOutput : ATObject, ICBOREncodable<GetFeedGeneratorsOutput>, IJsonEncodable<GetFeedGeneratorsOutput>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="GetFeedGeneratorsOutput"/> class.
        /// </summary>
        /// <param name="feeds"></param>
        public GetFeedGeneratorsOutput(List<FishyFlip.Lexicon.App.Bsky.Feed.GeneratorView> feeds = default)
        {
            this.Feeds = feeds;
            this.Type = "app.bsky.feed.getFeedGenerators#GetFeedGeneratorsOutput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="GetFeedGeneratorsOutput"/> class.
        /// </summary>
        public GetFeedGeneratorsOutput()
        {
            this.Type = "app.bsky.feed.getFeedGenerators#GetFeedGeneratorsOutput";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="GetFeedGeneratorsOutput"/> class.
        /// </summary>
        public GetFeedGeneratorsOutput(CBORObject obj)
        {
            if (obj["feeds"] is not null) this.Feeds = obj["feeds"].Values.Select(n =>new FishyFlip.Lexicon.App.Bsky.Feed.GeneratorView(n)).ToList();
        }

        /// <summary>
        /// Gets or sets the feeds.
        /// </summary>
        [JsonPropertyName("feeds")]
        [JsonRequired]
        public List<FishyFlip.Lexicon.App.Bsky.Feed.GeneratorView> Feeds { get; set; }

        public const string RecordType = "app.bsky.feed.getFeedGenerators#GetFeedGeneratorsOutput";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Feed.GetFeedGeneratorsOutput>)SourceGenerationContext.Default.AppBskyFeedGetFeedGeneratorsOutput);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Feed.GetFeedGeneratorsOutput>)SourceGenerationContext.Default.AppBskyFeedGetFeedGeneratorsOutput);
        }

        public static new GetFeedGeneratorsOutput FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Feed.GetFeedGeneratorsOutput>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Feed.GetFeedGeneratorsOutput>)SourceGenerationContext.Default.AppBskyFeedGetFeedGeneratorsOutput)!;
        }

         /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

         /// <inheritdoc/>
        public static new GetFeedGeneratorsOutput FromCBORObject(CBORObject obj)
        {
            return new GetFeedGeneratorsOutput(obj);
        }

    }
}

