// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Feed
{
    /// <summary>
    /// Allow replies from actors on a list.
    /// </summary>
    public partial class ListRule : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="ListRule"/> class.
        /// </summary>
        /// <param name="list"></param>
        public ListRule(FishyFlip.Models.ATUri list = default)
        {
            this.List = list;
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="ListRule"/> class.
        /// </summary>
        public ListRule()
        {
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="ListRule"/> class.
        /// </summary>
        public ListRule(CBORObject obj)
        {
            if (obj["list"] is not null) this.List = obj["list"].ToATUri();
        }

        /// <summary>
        /// Gets or sets the list.
        /// </summary>
        [JsonPropertyName("list")]
        [JsonRequired]
        [JsonConverter(typeof(FishyFlip.Tools.Json.ATUriJsonConverter))]
        public FishyFlip.Models.ATUri List { get; set; }

        /// <summary>
        /// Gets the ATRecord Type.
        /// </summary>
        [JsonPropertyName("$type")]
        public override string Type => "app.bsky.feed.threadgate#listRule";

        public const string RecordType = "app.bsky.feed.threadgate#listRule";

        public override string ToJson()
        {
            return JsonSerializer.Serialize<FishyFlip.Lexicon.App.Bsky.Feed.ListRule>(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Feed.ListRule>)SourceGenerationContext.Default.AppBskyFeedListRule)!;
        }

        public static ListRule FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Feed.ListRule>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Feed.ListRule>)SourceGenerationContext.Default.AppBskyFeedListRule)!;
        }
    }
}

