// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Feed
{
    public partial class NotFoundPost : ATObject, ICBOREncodable<NotFoundPost>, IJsonEncodable<NotFoundPost>, IParsable<NotFoundPost>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="NotFoundPost"/> class.
        /// </summary>
        /// <param name="uri"></param>
        /// <param name="notFound"></param>
        public NotFoundPost(FishyFlip.Models.ATUri uri = default, bool notFound = default)
        {
            this.Uri = uri;
            this.NotFound = notFound;
            this.Type = "app.bsky.feed.defs#notFoundPost";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="NotFoundPost"/> class.
        /// </summary>
        public NotFoundPost()
        {
            this.Type = "app.bsky.feed.defs#notFoundPost";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="NotFoundPost"/> class.
        /// </summary>
        public NotFoundPost(CBORObject obj)
        {
            if (obj["uri"] is not null) this.Uri = obj["uri"].ToATUri();
            if (obj["notFound"] is not null) this.NotFound = obj["notFound"].AsBoolean();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the uri.
        /// </summary>
        [JsonPropertyName("uri")]
        [JsonRequired]
        [JsonConverter(typeof(FishyFlip.Tools.Json.ATUriJsonConverter))]
        public FishyFlip.Models.ATUri Uri { get; set; }

        /// <summary>
        /// Gets or sets the notFound.
        /// </summary>
        [JsonPropertyName("notFound")]
        [JsonRequired]
        public bool NotFound { get; set; }

        public const string RecordType = "app.bsky.feed.defs#notFoundPost";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Feed.NotFoundPost>)SourceGenerationContext.Default.AppBskyFeedNotFoundPost);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Feed.NotFoundPost>)SourceGenerationContext.Default.AppBskyFeedNotFoundPost);
        }

        public static new NotFoundPost FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Feed.NotFoundPost>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Feed.NotFoundPost>)SourceGenerationContext.Default.AppBskyFeedNotFoundPost)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new NotFoundPost FromCBORObject(CBORObject obj)
        {
            return new NotFoundPost(obj);
        }

        /// <inheritdoc/>
        public static NotFoundPost Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<NotFoundPost>(s, (JsonTypeInfo<NotFoundPost>)SourceGenerationContext.Default.AppBskyFeedNotFoundPost)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out NotFoundPost result)
        {
            result = JsonSerializer.Deserialize<NotFoundPost>(s, (JsonTypeInfo<NotFoundPost>)SourceGenerationContext.Default.AppBskyFeedNotFoundPost);
            return result != null;
        }
    }
}

