// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.Blue.Zio.Atfile
{
    /// <summary>
    /// Unknown metadata for an uploaded file.
    /// </summary>
    public partial class Unknown : ATObject
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="Unknown"/> class.
        /// </summary>
        /// <param name="reason"></param>
        public Unknown(string? reason = default)
        {
            this.Reason = reason;
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="Unknown"/> class.
        /// </summary>
        public Unknown()
        {
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="Unknown"/> class.
        /// </summary>
        public Unknown(CBORObject obj)
        {
            if (obj["reason"] is not null) this.Reason = obj["reason"].AsString();
        }

        /// <summary>
        /// Gets or sets the reason.
        /// </summary>
        [JsonPropertyName("reason")]
        public string? Reason { get; set; }

        /// <summary>
        /// Gets the ATRecord Type.
        /// </summary>
        [JsonPropertyName("$type")]
        public override string Type => "blue.zio.atfile.meta#unknown";

        public const string RecordType = "blue.zio.atfile.meta#unknown";

        public override string ToJson()
        {
            return JsonSerializer.Serialize<FishyFlip.Lexicon.Blue.Zio.Atfile.Unknown>(this, (JsonTypeInfo<FishyFlip.Lexicon.Blue.Zio.Atfile.Unknown>)SourceGenerationContext.Default.BlueZioAtfileUnknown)!;
        }

        public static Unknown FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.Blue.Zio.Atfile.Unknown>(json, (JsonTypeInfo<FishyFlip.Lexicon.Blue.Zio.Atfile.Unknown>)SourceGenerationContext.Default.BlueZioAtfileUnknown)!;
        }
    }
}

