// <auto-generated />
// This file was generated by FFSourceGen.
// Do not modify this file.

#nullable enable annotations
#nullable disable warnings

namespace FishyFlip.Lexicon.App.Bsky.Draft
{
    /// <summary>
    /// One of the posts that compose a draft.
    /// </summary>
    public partial class DraftPost : ATObject, ICBOREncodable<DraftPost>, IJsonEncodable<DraftPost>, IParsable<DraftPost>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="DraftPost"/> class.
        /// </summary>
        /// <param name="text">The primary post content. It has a higher limit than post contents to allow storing a larger text that can later be refined into smaller posts.</param>
        /// <param name="labels">Self-label values for this post. Effectively content warnings.
        /// <br/> Union Types: <br/>
        /// <see cref="FishyFlip.Lexicon.Com.Atproto.Label.SelfLabels"/> (com.atproto.label.defs#selfLabels) <br/>
        /// </param>
        /// <param name="embedImages"></param>
        /// <param name="embedVideos"></param>
        /// <param name="embedExternals"></param>
        /// <param name="embedRecords"></param>
        public DraftPost(string text = default, FishyFlip.Lexicon.Com.Atproto.Label.SelfLabels? labels = default, List<FishyFlip.Lexicon.App.Bsky.Draft.DraftEmbedImage>? embedImages = default, List<FishyFlip.Lexicon.App.Bsky.Draft.DraftEmbedVideo>? embedVideos = default, List<FishyFlip.Lexicon.App.Bsky.Draft.DraftEmbedExternal>? embedExternals = default, List<FishyFlip.Lexicon.App.Bsky.Draft.DraftEmbedRecord>? embedRecords = default)
        {
            this.Text = text;
            this.Labels = labels;
            this.EmbedImages = embedImages;
            this.EmbedVideos = embedVideos;
            this.EmbedExternals = embedExternals;
            this.EmbedRecords = embedRecords;
            this.Type = "app.bsky.draft.defs#draftPost";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="DraftPost"/> class.
        /// </summary>
        public DraftPost()
        {
            this.Type = "app.bsky.draft.defs#draftPost";
        }


        /// <summary>
        /// Initializes a new instance of the <see cref="DraftPost"/> class.
        /// </summary>
        public DraftPost(CBORObject obj)
        {
            if (obj["text"] is not null) this.Text = obj["text"].AsString();
            if (obj["labels"] is not null) this.Labels = new FishyFlip.Lexicon.Com.Atproto.Label.SelfLabels(obj["labels"]);
            if (obj["embedImages"] is not null) this.EmbedImages = obj["embedImages"].Values.Select(n =>new FishyFlip.Lexicon.App.Bsky.Draft.DraftEmbedImage(n)).ToList();
            if (obj["embedVideos"] is not null) this.EmbedVideos = obj["embedVideos"].Values.Select(n =>new FishyFlip.Lexicon.App.Bsky.Draft.DraftEmbedVideo(n)).ToList();
            if (obj["embedExternals"] is not null) this.EmbedExternals = obj["embedExternals"].Values.Select(n =>new FishyFlip.Lexicon.App.Bsky.Draft.DraftEmbedExternal(n)).ToList();
            if (obj["embedRecords"] is not null) this.EmbedRecords = obj["embedRecords"].Values.Select(n =>new FishyFlip.Lexicon.App.Bsky.Draft.DraftEmbedRecord(n)).ToList();
            if (obj["$type"] is not null) this.Type = obj["$type"].AsString();
        }

        /// <summary>
        /// Gets or sets the text.
        /// <br/> The primary post content. It has a higher limit than post contents to allow storing a larger text that can later be refined into smaller posts.
        /// </summary>
        [JsonPropertyName("text")]
        [JsonRequired]
        public string Text { get; set; }

        /// <summary>
        /// Gets or sets the labels.
        /// <br/> Self-label values for this post. Effectively content warnings.
        /// <br/> Union Types: <br/>
        /// <see cref="FishyFlip.Lexicon.Com.Atproto.Label.SelfLabels"/> (com.atproto.label.defs#selfLabels) <br/>
        /// </summary>
        [JsonPropertyName("labels")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public FishyFlip.Lexicon.Com.Atproto.Label.SelfLabels? Labels { get; set; }

        /// <summary>
        /// Gets or sets the embedImages.
        /// </summary>
        [JsonPropertyName("embedImages")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public List<FishyFlip.Lexicon.App.Bsky.Draft.DraftEmbedImage>? EmbedImages { get; set; }

        /// <summary>
        /// Gets or sets the embedVideos.
        /// </summary>
        [JsonPropertyName("embedVideos")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public List<FishyFlip.Lexicon.App.Bsky.Draft.DraftEmbedVideo>? EmbedVideos { get; set; }

        /// <summary>
        /// Gets or sets the embedExternals.
        /// </summary>
        [JsonPropertyName("embedExternals")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public List<FishyFlip.Lexicon.App.Bsky.Draft.DraftEmbedExternal>? EmbedExternals { get; set; }

        /// <summary>
        /// Gets or sets the embedRecords.
        /// </summary>
        [JsonPropertyName("embedRecords")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public List<FishyFlip.Lexicon.App.Bsky.Draft.DraftEmbedRecord>? EmbedRecords { get; set; }

        public const string RecordType = "app.bsky.draft.defs#draftPost";

        public override string ToJson()
        {
            return JsonSerializer.Serialize(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Draft.DraftPost>)SourceGenerationContext.Default.AppBskyDraftDraftPost);
        }

        public override byte[] ToUtf8Json()
        {
            return JsonSerializer.SerializeToUtf8Bytes(this, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Draft.DraftPost>)SourceGenerationContext.Default.AppBskyDraftDraftPost);
        }

        public static new DraftPost FromJson(string json)
        {
            return JsonSerializer.Deserialize<FishyFlip.Lexicon.App.Bsky.Draft.DraftPost>(json, (JsonTypeInfo<FishyFlip.Lexicon.App.Bsky.Draft.DraftPost>)SourceGenerationContext.Default.AppBskyDraftDraftPost)!;
        }

        /// <inheritdoc/>
        public override CBORObject ToCBORObject()
        {
            using var jsonStream = new MemoryStream(Encoding.UTF8.GetBytes(this.ToJson()));
            return CBORObject.ReadJSON(jsonStream);
        }

        /// <inheritdoc/>
        public static new DraftPost FromCBORObject(CBORObject obj)
        {
            return new DraftPost(obj);
        }

        /// <inheritdoc/>
        public static DraftPost Parse(string s, IFormatProvider? provider)
        {
            return JsonSerializer.Deserialize<DraftPost>(s, (JsonTypeInfo<DraftPost>)SourceGenerationContext.Default.AppBskyDraftDraftPost)!;
        }

        /// <inheritdoc/>
        public static bool TryParse(string? s, IFormatProvider? provider, out DraftPost result)
        {
            result = JsonSerializer.Deserialize<DraftPost>(s, (JsonTypeInfo<DraftPost>)SourceGenerationContext.Default.AppBskyDraftDraftPost);
            return result != null;
        }
    }
}

